### ISSUE TITLE
Stuck at starting dev server

### ISSUE THREAD

**Issue by mira-thakkar** [stackblitz/core#2659] opened 2023-07-27 06:59 UTC
I tried to fork one of prime-react example in Stackblits, and it's keep saying Starting Dev Server

**Comment by melloware** [comment] 2023-07-27 13:47
Whoops I just reported the same thing: https://github.com/stackblitz/core/issues/2660

**Comment by jahnli** [comment] 2023-07-28 08:18
Always install

![image](https://github.com/stackblitz/core/assets/20943608/f55222d7-26a1-449b-8a41-a0410c98eb37)

**Comment by kc0tlh** [comment] 2023-08-24 17:08
Closing as duplicate of #2660 which has been resolved.

**Closed by kc0tlh** 2023-08-24 17:08 UTC
