### ISSUE TITLE
Error when open project from github

### ISSUE THREAD

**Issue by Djaler** [stackblitz/core#1677] opened 2021-11-29 08:23 UTC
I tried to open project by link https://stackblitz.com/github/Djaler/pinia-vue-2-store-to-refs

![image](https://user-images.githubusercontent.com/7964583/143832403-449afdc5-78b0-4290-be00-bf18187ba923.png)

**Comment by EricSimons** [comment] 2021-11-29 17:22
Not sure why this didn't work properly, but I added the ?preset=node to the URL and it busted the (bad) cache and seems to boot properly now: https://stackblitz.com/github/Djaler/pinia-vue-2-store-to-refs?preset=node

Closing for now but will continue investigating root cause on our side.

**Closed by EricSimons** 2021-11-29 17:22 UTC
