### ISSUE TITLE
Screen not visible

### ISSUE THREAD

**Issue by vk-kashyap** [stackblitz/core#2768] opened 2023-10-08 12:59 UTC
a tab tab visible in the screen, 60% of page is blacked out

**Comment by fvsch** [comment] 2023-10-08 16:21
Hi @vk-kashyap,

Which browser and browser version are you using?

This sounds similar to other reports that seem caused by using an outdated version of Chrome (or other browsers). See #2755, #2757.

**Comment by fvsch** [comment] 2023-10-09 12:26
This should now be fixed in older Chrome versions.

We do recommend using an up-to-date versions of Chrome, Firefox or Safari to use StackBlitz.

**Closed by fvsch** 2023-10-09 12:26 UTC
