### ISSUE TITLE
Issue in the project

### ISSUE THREAD

**Issue by sai3241** [stackblitz/core#2777] opened 2023-10-10 11:57 UTC
Hi Team,ui os not displaying properly  and this is the project stackbliz https://stackblitz.com/edit/react-xt738y?file=src%2Flayouts%2FFixed%2Fcomponents%2FTopbar%2FTopbar.js  its loading and I am doing in google chrome

**Comment by fvsch** [comment] 2023-10-10 12:18
Closing as a duplicate of your previous issue, #2776.

**Closed by fvsch** 2023-10-10 12:18 UTC
