### ISSUE TITLE
Some questions about private usage

### ISSUE THREAD

**Issue by Peng-YM** [stackblitz/core#604] opened 2018-07-16 09:14 UTC
Is it possible to deploy stackblitz in my own server or use it in company? If it is possible, could you provide some extra information about the environment setup? Thanks!

**Comment by durvalrafael** [comment] 2018-09-14 05:37
I have this same doubt over here

**Comment by samtsai** [comment] 2018-12-17 18:17
This is a duplicate of #134 There's a little more discussion in there if we wanted to follow that issue instead.

**Comment by beeman** [comment] 2019-03-27 03:01
Since last week we added the option to sync projects to (private) GitHub repos and making projects private.

![stackblitz-privacy](https://user-images.githubusercontent.com/36491/55047388-9f138200-5012-11e9-92a3-3acffb2683ff.gif)


Closing this issue as self-hosting the server-side of StackBlitz is not something that's on the roadmap for the foreseeable future.

**Closed by beeman** 2019-03-27 03:01 UTC
Labels: question

**Comment by JustinBobby007** [comment] 2019-04-09 03:55
It's useful to support deploying stackblitz in one's own server or use it in company because many projects in corporate are behind in firewalls and have not access to external sites.
