### ISSUE TITLE
file not found.

### ISSUE THREAD

**Issue by divakaruser** [stackblitz/core#2602] opened 2023-06-26 18:01 UTC
even i define proper path for css and images its showing error.

**Comment by fvsch** [comment] 2023-07-03 14:07
Hi @divakaruser,

To take a look at your issue we will need more information, including:

1. a link to a StackBlitz project showing your issue;
2. a description of the actions that need to be done on that project to reproduce the issue (also called “steps to reproduce”).

**Comment by kc0tlh** [comment] 2023-08-24 18:45
Closing due to lack of reproduction.

**Closed by kc0tlh** 2023-08-24 18:45 UTC
Labels: Status: Needs a reproduction link, Type: Unclear
