### ISSUE TITLE
Firebase deploy not working

### ISSUE THREAD

**Issue by MrYanMYN** [stackblitz/core#2554] opened 2023-06-05 11:03 UTC
i've been trying to deploy to firebase and it's just stuck on the "deploying" loading infinitely. 

Project link: https://stackblitz.com/edit/angular-cesium-polygon-editor-example-mxfhhc?file=README.md

**Comment by HeyGarrison** [comment] 2024-01-22 22:45
Duplicate of #2933

**Closed by HeyGarrison** 2024-01-22 22:45 UTC
