### ISSUE TITLE
Dependencies autocomplete

### ISSUE THREAD

**Issue by gkiely** [stackblitz/core#141] opened 2017-09-14 10:48 UTC
When I want to add a package, I type it into dependencies and add it.

But sometimes I can't remember the name exactly so I have to go to npm, search for it and then copy and paste it into stackblitz.

What would be great is if when typing in a dependency it shows you an autocomplete of possible names.
Bonus points for also showing or ordering by the the number of downloads.

**Comment by EricSimons** [comment] 2017-09-14 17:58
Excellent idea — adding this to our roadmap now! Thanks :)

**Comment by sulco** [comment] 2021-02-09 12:59
This seems like a duplicate of #46 - closing

**Closed by sulco** 2021-02-09 12:59 UTC
Labels: enhancement
