### ISSUE TITLE
iframe heads are not removed when page is reloaded

### ISSUE THREAD

**Issue by crutchcorn** [stackblitz/core#596] opened 2018-07-09 18:29 UTC
Currently, when I make changes to my HTML - I have my iframe DOM reload. However, whereareas it unloads my `body` tag and replaces it with a newer one - it does not do so for the `head` of that iframe

![image](https://user-images.githubusercontent.com/9100169/42468982-3d8345e4-836b-11e8-8bd9-334287e96a70.png)

Because of this, I often have MANY MANY MANY duplicated classes when working with the element inspector for that iFrame

**Comment by tiliev** [comment] 2018-07-10 06:55
@crutchcorn, I cannot reproduce it. Can you share a StackBlitz sample in which it can be reproduced?

**Comment by crutchcorn** [comment] 2018-07-10 15:53
https://stackblitz.com/edit/table-fun

**Comment by purplem1lk** [comment] 2021-04-27 13:18
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

**Closed by purplem1lk** 2021-04-27 13:18 UTC
Labels: bug
