### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by kanavbhatia** [stackblitz/core#2256] opened 2023-01-12 15:17 UTC
Whenever new dependencies are installed like @angular/cdk or @angular/material, dependencies are not getting installed. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33593937/212104398-1da81e88-eabd-4bb3-99d5-e174620a5947.png">
Initially installing dependencies come, then running NGCC and its stuck forever. 
Even if page is restarted then running dev server comes and it never installs. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33593937/212105430-c6f0e6f1-0500-4381-a75d-e1ea0aacb2d1.png">

**Comment by markwhitfeld** [comment] 2023-01-18 19:59
Duplicate of #2253
Fix was released on Monday and there has been no recurrence.
This should be resolved now. Closing issue.
If this issue is something different then please reopen an issue with more details and a reproduction.

**Closed by markwhitfeld** 2023-01-18 19:59 UTC
