### ISSUE TITLE
Firefox, frontend static template not working

### ISSUE THREAD

**Issue by filipw01** [stackblitz/core#2000] opened 2022-08-23 07:29 UTC
After opening the frontend static template it's displaying the following error in Firefox 103. It works correctly in chrome
```
Error occurred:
Error: ENOENT: No such file or directory., '/~'
```
Link to example https://stackblitz.com/edit/web-platform-3pf78s?file=index.html

**Comment by filipw01** [comment] 2022-08-23 07:30
What a round issue number 😄

**Comment by alexhampu** [comment] 2022-08-23 17:25
The same thing happens to me on a new Web Platform fork on Firefox 103.0.2

**Comment by andsheterliak** [comment] 2022-11-23 03:50
Duplicate of #1679

**Comment by fvsch** [comment] 2023-04-11 19:02
Closing as a duplicate of #1679.

**Closed by fvsch** 2023-04-11 19:02 UTC
