### ISSUE TITLE
Out of stack space on Edge.

### ISSUE THREAD

**Issue by surc54** [stackblitz/core#787] opened 2018-11-15 15:26 UTC
![image](https://user-images.githubusercontent.com/34602379/48562713-c7e77600-e8c0-11e8-82cb-d36b82bd6bd3.png)

URL: https://stackblitz.com/angular/plpobjnvkag?file=app%2Fsidenav-open-close-example.ts

**Comment by apai4** [comment] 2018-11-16 18:33
@surc54 Thanks for reporting this! I was able to view that URL without errors using IE11 & Edge on Windows 10, so this issue might depend on what extensions you have installed or how much system resources you have available at the time.

@tiliev could you try this URL on Edge and let us know if it works for you? Thanks!

**Comment by tiliev** [comment] 2018-11-18 23:14
It works correctly on my side, too.
![capture](https://user-images.githubusercontent.com/6439482/48679399-7842cc00-eb98-11e8-9f78-0a0fe0012f82.PNG)

**Comment by silicon8** [comment] 2018-12-02 21:31
I'm having the same issue. None of the examples work.

Using the following browser:
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

**Comment by AsafAgranat** [comment] 2019-01-16 16:15
Same happening here, on:
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

**Comment by NickMurphy** [comment] 2019-01-30 09:55
I'm having the same issue.

Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Windows Version 10.0.17763 Build 17763

**Comment by kevin12314** [comment] 2019-01-31 01:52
I got same issue.

Microsoft Edge 44.18323.1000.0
Microsoft EdgeHTML 18.18323

**Comment by desertrambler** [comment] 2019-02-24 22:47
I also got the same issue today. In order to verify that it has nothing to do with any extensions that I have loaded, I also tried running this in a new Microsoft Edge InPrivate Window, and I still get the out of stack space message.

Is there anyone looking at fixing this?

Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Windows 10 Pro Version 1809 OS Build 17763.316

**Comment by Zymex** [comment] 2019-03-13 14:57
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

Same issue.

**Comment by wzheng2310** [comment] 2019-05-07 23:39
Same here. 
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

**Comment by Zymex** [comment] 2019-05-08 00:51
> Same here.
> Microsoft Edge 44.17763.1.0
> Microsoft EdgeHTML 18.17763
> 
> It seems all the people here reporting the bug are using Edge 44.x
I agree
I mean is it confirmed working in any version other than 42.17134.1.0?

**Comment by hfournier** [comment] 2019-06-05 16:40
Same here.
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Windows 10 Pro Version 1809 OS Build 17763.529

**Comment by mathieuhasum** [comment] 2019-09-27 15:04
Same issue today.

Microsoft Edge 44.17763.1.0

**Comment by lostrepo** [comment] 2019-10-02 07:35
Probably, won't be fixed in Edge because they plan to switch to Chromium as base. Thread about similar issue:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19075248/

**Note**: _Tests - not real application. Was testing WebAssembly polyfill which uses recursion for parsing (fails on 40+ chained function calls in WebWorker and can't be used). So Function Scope sizes contribute to this issue._

**Tests**:
Recursive call chain length for **EdgeHTML 18.18362** / **Chrome 77** inside WebWorker with ten 7-10 line functions and 7 variables. In normal window over 1000 / 12000,
If function performs long operation like pushing 1000000 random values into array function call chain length can be over 200 / 10000.
``` javascript
// dies with chain length of 160 / 6366
var i = 0;
function req0(){
	console.log(i++);
	req0();
}
req0();

// dies with chain length of 110 / 2893
var i = 0;
function req1(){
	console.log(i++);
	req1.call(this);
}
req1();
```

Hope this info will help you decide what to do with this bug.
Was searching for solution to this Edge bug and there is only one so far - integrate own stack.

**Closed as completed** 2021-05-04 17:06 UTC
