### ISSUE TITLE
Export Feature does not work!

### ISSUE THREAD

**Issue by parkychow** [stackblitz/core#377] opened 2018-03-29 18:18 UTC
I export the source code of "https://stackblitz.com/angular/ggqreenqvae?file=app%2Ftable-selection-example.ts"

When I run "ng server", it has error... it seems using webpack is very trouble while default Angular CLI is working properly.

RROR in Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to
the plugins options.
    at Object.resolveEntryModuleFromMain (C:\code\TablewithSelection\node_modules\@ngtools\webpack\src\entry_resolver.js:131:11)
    at Promise.resolve.then.then (C:\code\TablewithSelection\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:240:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by flyer1** [comment] 2018-05-16 19:41
I was getting errors b/c inside the src folder was another src folder. The latter had my app folder in there plus some others. I moved all that was in the latter to the former (ie: combined the 2 src folders into 1) and this resolved the issue.

**Comment by intergalactickraigor** [comment] 2018-08-08 19:13
Stackblitz still exports nested src folders.

Is this issue going to be resolved?  I am seeing this problem too.  And it is also causing problems with Angular's examples as seen in Angular's repository.

#https://github.com/angular/angular/issues/23962

**Comment by intergalactickraigor** [comment] 2018-08-08 19:20
![screen shot 2018-08-08 at 3 18 28 pm](https://user-images.githubusercontent.com/4259428/43859379-70c18f40-9b1e-11e8-9006-242d8d62621a.png)

nested src folders on Angular projects.  It will not work unless you rearrange the files before running commands.

**Comment by ChenReuven** [comment] 2018-08-20 10:36
@intergalactickraigor  Thanks it working :)

**Comment by intergalactickraigor** [comment] 2018-08-20 15:16
I submitted a pull request to attempt to resolve this to the stackblitz/angular-cli repository: **https://github.com/stackblitz/angular-cli-template/pull/7**
however, I just noticed that the default angular application is now using angular 6, so I am not sure if this repository is still the source of truth for the starters.

Regardless, the issue is that `blitz_export.json` needs to not output to "src", as this folder is generated with a package.json and everything.  It should export to "/" .

**Comment by methodbox** [comment] 2019-06-15 17:19
I had this same issue. I wanted to use the latest Angular 8 as well. Here's my solution.

## Export the project normally by just downloading and extracting the zip. Replace `dependencies` and `devDependencies` by making note of all the deps and installing them individually (commands below).

```bash
npm install --save rxjs tslib core-js zone.js jasmine-core @angular/core @angular/forms @angular/common @angular/router jasmine-marbles @angular/compiler web-animations-js @angular/animations @angular/platform-browser angular-in-memory-web-api @angular/platform-browser-dynamic
```
```bash
npm install --save-dev @angular-devkit/build-angular @angular/cli @angular/compiler-cli @angular/language-service @types/jasmine @types/jasminewd2 @types/node codelyzer jasmine-core jasmine-spec-reporter karma karma-chrome-launcher karma-coverage-istanbul-reporter karma-jasmine karma-jasmine-html-reporter protractor ts-node tslint typescript
```

## Modify the `angular.json` file to reference the `tsconfig.app.json` in the correct location. Edit the `tsconfig` value under the `architect` block.

```json
...
"architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            ...
```

## Edit the `src/polyfills.ts` file to reference the latest `core-js` module.

```js
import 'core-js/es/reflect';
//import 'core-js/es7/reflect';
```

Then you can serve the app with `npm start` and it will run on `localhost:4200` - I'm putting this here because there's no output indicating where the hell it's running ;).

Hope that helps.

**Comment by kc0tlh** [comment] 2023-08-23 09:33
This should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow). More information in Github issue #9

**Closed by kc0tlh** 2023-08-23 09:33 UTC
