### ISSUE TITLE
Support latest versions of node

### ISSUE THREAD

**Issue by hpx7** [stackblitz/core#1622] opened 2021-09-29 18:04 UTC
### **Is your feature request related to a problem? Please describe.**
I need some newer node features, mostly around ESM and loaders. My app's minimum node requirement is 15.0.

### **Describe the solution you'd like**
Support for node v15 or v16.

### **Additional context**
Add any context or screenshots about the feature request here.

**Comment by trentprynn** [comment] 2021-10-30 15:01
I would also very much like a way to configure the nodejs version used by the stackblitz webcontainer. Currently I primarily use stackblitz as a way to share bug reproductions (it's awesome, thank you!) and I'm having a problem I'm relatively sure is related node 16 that I cannot reproduce / share because stackblitz (as far as I can tell) only allows you to use node 14

**Comment by markwhitfeld** [comment] 2021-11-02 10:14
@hpx7 I am in the process of adding this support to StackBlitz v1 right now. I will keep you posted.

@trentprynn I think that it would be best to log this issue under https://github.com/stackblitz/webcontainer-core. This is the primary place that we track the webcontainer feature requests and issues.

**Comment by markwhitfeld** [comment] 2022-01-25 18:50
I am closing this issue in favour of https://github.com/stackblitz/webcontainer-core/issues/560

StackBlitz V1 does not run node, but provides an in browser javascript execution environment for well known project types.
We have recently added the ability for StackBlitz V1 to support ESM and the `package.exports` field for node packages.

StackBlitz V2 (WebContainers), on the other hand, runs a full node execution environment in the browser, and as tracked in the issue above (in the repo where issues for WebContainer are tracked), support for Node 16 is currently WIP and will be landing this quarter. There is custom work required with every release of Node due to the changes in the underlying internal APIs and feature set offered. Keeping up with Node is a constant activity for the team.

**Closed by markwhitfeld** 2022-01-25 18:50 UTC
Labels: Type: Feature Request, Status: Triage
