### ISSUE TITLE
cannot install npm package

### ISSUE THREAD

**Issue by epanlauw** [stackblitz/core#2255] opened 2023-01-12 15:08 UTC
I try to install bootstrap / ngx-bootstrap and always stuck in running ngcc , i tried to open up inspect element and found 
"uncaught (in promise) syntaxerror: cannot use 'import.meta' outside a module"

**Comment by markwhitfeld** [comment] 2023-01-18 19:58
Duplicate of #2253
Fix was released on Monday and there has been no recurrence.
This should be resolved now. Closing issue.
If this issue is something different then please reopen an issue with more details and a reproduction.

**Closed by markwhitfeld** 2023-01-18 19:58 UTC
