### ISSUE TITLE
off screen only showing

### ISSUE THREAD

**Issue by kuttralaganesh** [stackblitz/core#2752] opened 2023-10-03 12:58 UTC
only showing off-screen only

**Comment by purplem1lk** [comment] 2023-10-03 13:17
Hi @kuttralaganesh, can you provide a StackBlitz project link, screenshot, or screencast of what you're seeing We'll need more info in order to help debug. Thanks!

**Comment by fvsch** [comment] 2023-10-08 16:22
Possible duplicate of #2755.

**Comment by fvsch** [comment] 2023-10-09 12:27
This should now be fixed in older Chrome versions.

We do recommend using an up-to-date versions of Chrome, Firefox or Safari to use StackBlitz.

**Closed by fvsch** 2023-10-09 12:27 UTC

**Comment by kuttralaganesh** [comment] 2023-10-09 12:31
Hi Florens, it is correct ,
I acknowledge the closure of issue #2752.
I update mac os after i update Chrome and all browser now working fine
 Thank you for your timely completion.

Best Regards,
Kuttrala Ganesh
