### ISSUE TITLE
Export Angular project contains 2 SRC directories 

### ISSUE THREAD

**Issue by jeffvg** [stackblitz/core#637] opened 2018-08-08 19:37 UTC
Angular export contains 2 src directories and duplicated scaffolding. Project does not run locally. 
Viewed angular 6 project via stackblitz and then exported it, project now contains angular 1.6.7 scaffold and my original angular 6

https://stackblitz.com/github/pxblue/simple-list/tree/ng6_simplelist

**Comment by tiliev** [comment] 2018-08-09 07:08
@jeffvg, thank you for your report. This is a known bug - https://github.com/stackblitz/core/issues/561.

**Comment by purplem1lk** [comment] 2021-04-27 13:30
This issue is a duplicate of #561 so we will keep all conversations and the resolution over there. This issue will be closed accordingly. If you have any questions, feel free to tag me here or update the conversation in #561. Thank you! :)

**Closed by purplem1lk** 2021-04-27 13:30 UTC
Labels: duplicate
