### ISSUE TITLE
Something went wrong with this repository.

### ISSUE THREAD

**Issue by donnypm** [stackblitz/core#1637] opened 2021-10-15 11:02 UTC
I don't know why I can't run it via stackblitz, even though when it's downloaded it doesn't have any problems

**Comment by fvsch** [comment] 2021-11-10 10:41
Closing this issue since it does not contain actionable information after 4 weeks.

Do create a new issue with more information on your problem (URL to a StackBlitz project, steps to reproduce), if it's still a current problem.

**Closed by fvsch** 2021-11-10 10:41 UTC
