### ISSUE TITLE
unlisting projects

### ISSUE THREAD

**Issue by RE-2** [stackblitz/core#838] opened 2019-01-11 22:44 UTC
Please provide an option to hide listing all projects publicly. 
While projects can still remain public, disabling listing them all, gives the owner better chance of limiting what to share explicitly. Currently if you share the link to one project you have given the rest as well.
This forces people to create multiple account or create anonymous projects

**Comment by beeman** [comment] 2019-03-27 03:03
Since last week we allow to set the privacy settings of your projects. It's not the same as unlisted, but it gives protection for projects that container private data.

![stackblitz-privacy](https://user-images.githubusercontent.com/36491/55047458-d7b35b80-5012-11e9-92f3-377fb2842c25.gif)

**Comment by purplem1lk** [comment] 2021-05-11 14:38
> Since last week we allow to set the privacy settings of your projects. It's not the same as unlisted, but it gives protection for projects that container private data.
> 
> ![stackblitz-privacy](https://user-images.githubusercontent.com/36491/55047458-d7b35b80-5012-11e9-92f3-377fb2842c25.gif)

Thank you for your patience - We recommend using the suggestion above to set the privacy settings of your projects and will be closing this issue accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by ffxsam** [comment] 2021-08-01 19:37
I would say this issue probably shouldn't be closed. Private is not the same as unlisted, which is what the original poster was asking for.

Is there any chance of getting an "unlisted" option? I paid for StackBlitz thinking it had this, but now that I realize it doesn't, I don't really see much value in it, as most of my use cases involve sharing semi-private code reproductions with other devs.

**Comment by purplem1lk** [comment] 2021-09-16 14:04
@ffxsam Based on the conversation that's going on in Discord, we're going to re-open this feature request and use it as our go-to issue for updates on this matter. Thanks!

**Comment by ffxsam** [comment] 2021-09-17 23:13
@purplem1lk Thanks, you rock!

**Closed** 2021-11-16 17:21 UTC

**Comment by Envek** [comment] 2021-11-16 20:07
@RE-2, @ffxsam, since today you can unlist some projects by choosing a new visibility level called “Secret” in projects settings.

Secret projects are available for everyone by direct link but don’t show up on the owner’s profile.

**Comment by ffxsam** [comment] 2021-11-16 20:17
Awesome, thanks! This is a huge improvement.
