### ISSUE TITLE
[BUGFIX] When app is in failed import state, emitted bundles need to include/respect errors

### ISSUE THREAD

**Issue by dwaq** [stackblitz/core#6] opened 2017-08-03 20:19 UTC
Would be nice if there was a full log of the build available. I'm seeing an error but it's not helping me without additional context.
![image](https://user-images.githubusercontent.com/1299430/28941870-605a4d2a-7867-11e7-86be-06a2de503358.png)
Specially the project I'm working at is https://stackblitz.com/edit/react-epqmud but opening that link just shows the default files, and not the files that I imported myself. Maybe there's an additional bug there?

**Comment by EricSimons** [comment] 2017-08-03 20:27
How did you get this error? This typically happens when an npm dependency is unable to be fetch during an install (often caused by bad network connection, etc). It's supposed to be descriptive about what failed to fetch though, so I'm not quite sure what's up here.

More info on how this occurred would be 👌

PS - please excuse our bugs; this tech is _super_ beta and we're working our tails off to squash them all 😓

**Comment by dwaq** [comment] 2017-08-03 20:31
I exported my project from here https://glitch.com/edit/#!/swift-crime and dropped the files into stackblitz. Then I manually added the dependencies from the `package.json`. I didn't see any errors as I typed them in, but it is possible something went wrong there.

Don't worry about the bugs. Just trying to make the product better by reporting them :smile:

**Comment by dwaq** [comment] 2017-08-03 20:32
Are the dependencies fetched server side or client side? I'm behind a proxy now that usually gives me errors fetching packages locally but I assumed your application would grab them directly.

**Comment by EricSimons** [comment] 2017-08-03 20:45
We really, really appreciate you reporting the bugs — it absolutely helps us make the product better, so please keep them coming! ❤️ (Hopefully there shouldn't be too many haha)

The dependencies are actually fetched _client_ side, so perhaps the proxy might be the problem. I'm going to try and download your glitch project, drag & drop into SB and see what happens. Currently swamped with the launch but I'll def repro this & nail down any issue by EOD 🙏

**Comment by EricSimons** [comment] 2017-08-04 03:29
^ will actually have to do this first thing tmrw morn- super super tired from all the launch stuff today 😴 Will report back when I've repro'd & ID root cause!

**Comment by dwaq** [comment] 2017-08-04 11:53
No rush. I was just playing around. Focus on what's important for getting this project off the ground. I'll come back when it's fixed. :+1:

**Comment by EricSimons** [comment] 2017-08-04 21:52
@dwaq this was actually just a UI bug on our end 😅  was worried it was something deeper lol. Shipping a fix shortly! You can view/fork the running version of your code here: https://stackblitz.com/edit/issue-6?file=index.js

**Comment by dwaq** [comment] 2017-08-07 14:21
Great, your code from https://stackblitz.com/edit/issue-6?file=index.js appears to be working for me

**Comment by EricSimons** [comment] 2017-08-08 01:05
This bug is now fixed in prod!

**Closed by EricSimons** 2017-08-08 01:05 UTC
Labels: bug
