### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by nizaroo712** [stackblitz/core#2057] opened 2022-09-15 06:29 UTC
good morning
The result does not appear on the console after executing the required code..
He always writes to me that you have to wait.. Note that the code is written correctly.
Please solve my problem.

**Comment by AleksandrSl** [comment] 2022-09-15 09:16
Hi, could you provide a link to your stackblitz playground, where we can reproduce the error?

**Comment by fvsch** [comment] 2023-07-03 13:17
Closing this issue since it does not have actionable information.

**Closed by fvsch** 2023-07-03 13:17 UTC
Labels: Status: Needs a reproduction link
