### ISSUE TITLE
Cant import project from github

### ISSUE THREAD

**Issue by Crispy-rw** [stackblitz/core#1538] opened 2021-07-12 16:58 UTC
I cant import a project from github. It saying i cant import a project without a package.json and the project i want to import is html and css

**Comment by Damato** [comment] 2021-07-26 07:53
How did you even get there, the link seems to be broken? 
`stackblitz.com/github/{GH_USERNAME}/{REPO_NAME}`

**Comment by purplem1lk** [comment] 2021-08-01 23:35
Hi @Crispy-rw - Thanks for your patience. Can you post the StackBlitz project link and/or GitHub repo so we can reproduce this, as well? :)

**Comment by kc0tlh** [comment] 2023-08-23 11:21
This issue should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! More info about the new integration in Github issue #2473

**Closed by kc0tlh** 2023-08-23 11:21 UTC
