### ISSUE TITLE
Editor extensions / plugins

### ISSUE THREAD

**Issue by e111077** [stackblitz/core#433] opened 2018-04-24 01:20 UTC
This may be a long shot, but it would be much appreciated for stackblitz to have a way from developers to write extensions (or support VS Code extensions).

We are using stackblitz to show users code samples on our docs site, but all of our workflows used tagged templates. e.g.
```js
render() {
  html`<div class="someClass">
    This will be highlighted properly in github but not stackblitz editor
  </div>`
}
```

Tagged template highlighting and intellisense was never added to VS Code core, but it was added in an [extension](https://marketplace.visualstudio.com/items?itemName=bierner.lit-html) by someone on the VS Code team.

**Comment by nukadelic** [comment] 2018-04-27 09:05
Currently relying on browser JS injection extensions ( Tempermonkey for chrome  ) to write my own plugins. That would be such a great addition

![capture](https://user-images.githubusercontent.com/6582633/39354272-7e853d6a-4a4d-11e8-8133-dc13bf65e0a0.PNG)

**Comment by seveves** [comment] 2018-05-29 13:52
Duplicate of #3 ... let's track the progress over there please

**Closed by seveves** 2018-05-29 13:52 UTC
