### ISSUE TITLE
Console disappears after toggling preview pane

### ISSUE THREAD

**Issue by dzhavat** [stackblitz/core#810] opened 2018-11-28 21:48 UTC
On initial load I can see the console and can open/close it. However, if I close the preview and open it again the console disappears completely. I think in that case it should still be there but in a closed state. Here's a handy gif:

![problem](https://user-images.githubusercontent.com/1096332/49184334-5b0fb980-f35f-11e8-88cc-67fd215599bb.gif)

**Comment by tiliev** [comment] 2018-12-05 11:46
@dzhavat, this works as expected on my side. Please share the blitz link, your OS and browser version.

**Comment by dzhavat** [comment] 2018-12-05 21:42
I'm sorry for not providing additional information. I opened the issue in a hurry. 

After testing a little bit I found out that the problem is most likely related to the `devtoolsheight=60` param that is part of the url. Here's [an example](https://stackblitz.com/edit/rxjs-vmlcgd?devtoolsheight=60).

If you remove the `devtoolsheight` from the url and toggle the preview, the console panel is still there. However, if the `devtoolsheight` is present then the console is visible only on initial load. Toggling the preview makes the console to disappear. 

Browser: Firefox v63
OS: Windows 10

**Comment by fvsch** [comment] 2022-06-01 16:07
I couldn't reproduce in Firefox 101 with https://stackblitz.com/edit/rxjs?devtoolsheight=60

Hopefully that means that this bug was fixed in recent years :)

Feel free to reopen if I missed it and this bug is still current.

**Closed by fvsch** 2022-06-01 16:07 UTC
Labels: Type: Bug

**Comment by BojanKogoj** [comment] 2024-02-21 08:36
@fvsch this bug is still present. Created new Angular project yesterday and console was never there.
https://stackblitz.com/edit/stackblitz-starters-saqwwz?file=src%2Fmain.ts

![slika](https://github.com/stackblitz/core/assets/634075/3f68687e-7cfb-4e1e-9494-86f3a86468c8)
