### ISSUE TITLE
Deleted github account, recreated, can't log in

### ISSUE THREAD

**Issue by errorx666** [stackblitz/core#1429] opened 2021-04-21 18:58 UTC
I had a StackBlitz account associated with my Github account.  I deleted my Github account.  Then I created a new one with the same email address and username.  Now I'm unable to login.  The message I receive is:

Yikes! It looks like there's already an account with your username or email

It tells me to change it on the original account, but the original account was deleted, so this is not possible.

**Comment by kc0tlh** [comment] 2021-04-21 19:33
@errorx666 sorry you encountered this issue (duplicate of #1402). 

If your new github username is _exactly_ the same as your old username we will need to completely delete your old StackBlitz account so you can create a new one. Please let me know what the associated email address is and I will have the team take care of this (you can also email the deletion request to hello@stackblitz.com).

If your new github username was at least 1 character different then your old username, then the following instructions would allow you to create a new StackBlitz account immediately: Update your Github email address to have a +github added to the end, so it is "unique". For example alex@gmail.com can be entered into github as alex+github@gmail.com and all email will still flow to the existing "alex" Gmail account.

**Comment by errorx666** [comment] 2021-04-21 19:57
@kc0tlh The username is exactly the same.  My email is error@error-unlimited.net.  Please delete my old account so I may create a new one.

**Comment by errorx666** [comment] 2021-05-15 14:09
Any update on this?

**Comment by kc0tlh** [comment] 2022-03-22 22:58
@apai4 / @HeyGarrison please delete [error@error-unlimited.net](mailto:error@error-unlimited.net) from StackBlitz.com completely and close this issue when complete. Thanks!

**Comment by kc0tlh** [comment] 2022-03-24 18:12
@errorx666, @HeyGarrison and I have confirmed that your account was deleted on May 18th 2021. Your last active login date is more recent than that so I am assuming you were able to successfully recreate your account! I will go ahead and close this issue, but let us know if we can be of additional assistance on this matter.

**Closed by kc0tlh** 2022-03-24 18:12 UTC
