### ISSUE TITLE
Import cannot find these files

### ISSUE THREAD

**Issue by david-commit** [stackblitz/core#2300] opened 2023-01-28 12:12 UTC
[Error Screen onLoad](https://i.postimg.cc/T3H7S8Yv/Screenshot-from-2023-01-28-15-09-04.png)

Doesnt load an import from GH correctly

**Comment by fvsch** [comment] 2023-01-30 09:02
Hi @david-commit.

Could you link to the repository you're trying to import, or the URL of the StackBlitz project that failed? I got the information from your screenshot, but as a general rule it's much easier for people to try to reproduce your problem if you include the information as text in your report.

It looks like StackBlitz is importing this repository with a default `create-react-app` preset, which runs on our [EngineBlock](https://developer.stackblitz.com/guides/user-guide/available-environments) environment. You can force using WebContainers instead, which might work better here, by adding `?preset=node` to the import URL:

https://stackblitz.com/github/david-commit/newlife-frontend/tree/david?preset=node

That being said, it might still run into a few issues:

- Looks like it's not finding the `chart.js` dependency. The project's code is importing from `chart.js`, but `chart.js` is not in the `package.json`'s dependencies. Looks like this project relies on `chart.js` being a transitive dependency of another package, which is not a good idea if you're going to import from it directly. This can trip up a number of package managers. Solution: `npm install chart.js`.

- The error shown in your screenshot is that it cannot import PNG files. That's probably because our GitHub importer does not import binary files, including PNGs and JPEGs, and only references those files as links back to the binary asset on GitHub. For instance, the `src/img/logo.png` file links back to:

https://cdn.jsdelivr.net/gh/david-commit/newlife-frontend@24637c0df42f4e7a18bf4cc29e2c51f03ffb1516/src/img/logo.png

So when Webpack tries to work with PNG/JPEG files, it's not finding the actual image data locally, which fails.

Sadly for now I think this is a limitation in our editor. Our upcoming editor, based on VS Code and WebContainers, might give you a better result, but fair warning that it's in beta currently!

https://pr.new/github.com/david-commit/newlife-frontend/tree/david

**Comment by kc0tlh** [comment] 2023-08-31 02:06
@david-commit this issue is now resolved in both the classic and new VS code editor! Thanks @fvsch for the analysis and testing links!

**Closed by kc0tlh** 2023-08-31 02:06 UTC
