### ISSUE TITLE
Firebase stuck at Firebase debploy

### ISSUE THREAD

**Issue by delrotf** [stackblitz/core#2516] opened 2023-05-12 07:44 UTC
![image](https://github.com/stackblitz/core/assets/25953312/14da556d-b435-4617-819d-683728f469ae)

**Comment by AniketNS** [comment] 2023-05-14 14:40
Can you please explain, what the actual problem is?

**Comment by HeyGarrison** [comment] 2024-01-22 22:45
Duplicate of #2933

**Closed by HeyGarrison** 2024-01-22 22:45 UTC
