### ISSUE TITLE
Preview pane in share model is broken

### ISSUE THREAD

**Issue by vicary** [stackblitz/core#2266] opened 2023-01-16 06:47 UTC
### **Description of Bug**
The _Preview_ collapsable pane in the share modal box fails to load the actual preview content.

### **Steps to Reproduce**

1. Fork or create any project
2. Click on _Share_
3. Open _Preview_

### **Expected Behavior**
The Preview pane loads my content.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/85772/212614079-5d793082-b369-4dc8-8fa2-b43cd87147a0.png)

When opening the preview pane, a particular console warning pops up.

![image](https://user-images.githubusercontent.com/85772/212614484-c3d02812-3186-4984-a743-16d6f4cd86b4.png)
_crbug/1173575, non-JS module files deprecated._

**Additional Context/Questions**
Browser: Chromium 109.0.5414.87

**Comment by kc0tlh** [comment] 2023-08-25 01:27
@vicary, thanks for the report! Closing as duplicate of @2452

**Closed by kc0tlh** 2023-08-25 01:27 UTC
Labels: Type: Bug, Status: Triage, Tech: WebContainer
