### ISSUE TITLE
[Chrome] Cannot create a simple React app.

### ISSUE THREAD

**Issue by fredyagomez** [stackblitz/core#900] opened 2019-03-18 22:43 UTC
Not sure what I am doing wrong but just clicking on create React sample does not work 
https://stackblitz.com/edit/react-ahrjth

Only chrome. Firefox seems to work fine.

BTW this is the error:
>Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document

**Comment by beeman** [comment] 2019-03-18 23:57
@fredyagomez this could be caused by a Chrome extension that blocks access to localStorage for our domains.

The quickest way to test this is by trying it in an incognito browser (with extensions disabled). 

You can also try if this [works](https://github.com/stackblitz/core/issues/162#issuecomment-357656965).

**Comment by fredyagomez** [comment] 2019-03-19 05:08
@beeman thanks for the quick response. It feels like an unnecessary step. How to make a default Chrome load the app without problem? I don't have knowledge about how to fix this unfortunately but would not like to say to my users this needs to be done previous to run this app.

**Comment by fredyagomez** [comment] 2019-03-19 05:12
@beeman BTW, wth is CodeYourFutureCO ? Saw a Colombian flag there :)

**Comment by purplem1lk** [comment] 2021-05-11 22:10
Thank you for your patience - This issue seems related to #162 so we will close this issue and continue the conversation/resolution over there, as there's more recent activity. If this issue persists, feel free to tag me or continue the conversation in #162. Thank you! :)

**Closed by purplem1lk** 2021-05-11 22:10 UTC
