### ISSUE TITLE
Browser is not able to load Stackblitz anymore

### ISSUE THREAD

**Issue by matproulx** [stackblitz/core#2462] opened 2023-04-05 17:31 UTC
In Chrome Version 112.0.5615.50 (Official Build) (64-bit) 
as well as Edge Version 111.0.1661.62 (Version officielle) (64 bits)
the Stackblitz browser window keeps showing "Starting dev server" but never loads.

**Comment by matproulx** [comment] 2023-04-05 17:40
Here is the link of my test : https://stackblitz.com/edit/angular-lk4pvz-kex9tp?file=app.component.ts

**Comment by john-fenton** [comment] 2023-04-05 21:16
@matproulx I believe this is a duplicate of #2455  that I raised the other day. `main.ts` has to be inside a `src` directory.

**Closed** 2023-04-06 18:13 UTC
