### ISSUE TITLE
bug: entrypoint for package cannot be found, even if it exists

### ISSUE THREAD

**Issue by paul-thebaud** [stackblitz/core#2991] opened 2024-02-28 21:53 UTC
### **Description of Bug**

I'm trying to create a JS stackblitz playground for my package `foscia`. But I'm getting the following error only with the Vanilla JS forked base project (non vite based):

```
The entrypoint for '@foscia/core' could not successfully be resolved. The file '/turbo_modules/@foscia/core@0.7.2/dist/index.mjs' does not exist. Please log an issue with the package author or check for an updated version of the package.
```

### **Steps to Reproduce**

1. Fork Vanilla JS project (non vite based)
2. Add `@foscia/core` package to dependencies
3. Try to import any exported member from `@foscia/core`

### Reproduction projects

- [Vanilla TS (non vite based): **working**](https://stackblitz.com/edit/foscia-ts-rest?file=playground.ts)
- [Vanilla JS (vite based): **working**](https://stackblitz.com/edit/vitejs-vite-tvnjs9?file=main.js,package.json)
- [Vanilla JS (non vite based): **breaking**](https://stackblitz.com/edit/foscia-js-rest-t594m5?file=index.js)

### **Expected Behavior**

Just like in with Vanilla TS (non vite based) or Vanilla JS (vite based): it should work without issue.

### **Screenshots/Screencast**
N/A

**Additional Context/Questions**

I'm using the Vanilla JS (non vite based) project because I wan't to have the devtools console to be quickly available and preopened in embedded views.

Thanks in advance!

**Comment by HeyGarrison** [comment] 2024-03-13 18:20
Hey there!

We recently moved all of our starters over to Webcontainers, and where we could also popped in Vite.

It looks like your project works with Webcontainers (https://node.new), which is our node environment. Moving forward, I would recommend using Webcontainers and not EngineBlock for all future work as it's a lot more full featured (as your reproductions are showing).

To see the differences here is our docs page on the subject: [https://developer.stackblitz.com/guides/user-guide/available-environments#frontmatter-title](https://developer.stackblitz.com/guides/user-guide/available-environments#frontmatter-title)

For now, I'll close this issue, but feel free to open a new issue if you have additional questions!

**Closed as completed by HeyGarrison** 2024-03-13 18:20 UTC
Labels: Type: Bug, Status: Triage

**Comment by paul-thebaud** [comment] 2024-03-13 19:50
Hello @HeyGarrison,
Thanks for this complete answer!
Just a last question about embedded views (iframe): is there a way (a query param?) to pre open the devtools console in the new Web container projects just like we could do in EngineBlock?
Thanks.

**Comment by HeyGarrison** [comment] 2024-04-01 15:10
Not at this time. However, I would recommend looking at a Vite plugin like this: [https://github.com/patak-dev/vite-plugin-terminal](https://github.com/patak-dev/vite-plugin-terminal)

We've found that that solve 90% of most use cases relating to the console.

**Comment by paul-thebaud** [comment] 2024-04-10 09:15
Thank you @HeyGarrison, I'll take a look on this soon!
