### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by ajspeller** [stackblitz/core#239] opened 2018-01-14 18:09 UTC
Love the IDE!

1) It would be great if the urls had an accompanying QR Code so that you could scan to load an existing project without having to type the URL.

2) Not sure how to upload or make use of needed project assets like images for example.

**Comment by kc0tlh** [comment] 2022-03-22 22:33
Thanks for the feedback! Closing as duplicate of issue #1485

**Closed by kc0tlh** 2022-03-22 22:33 UTC
