### ISSUE TITLE
No image Upload 

### ISSUE THREAD

**Issue by Jexcode** [stackblitz/core#2210] opened 2022-12-07 17:24 UTC
I'm very satisfied with the software of this project, it's really been a nice code editor to use however I discovered I can't upload files or images from device to it and I not really sure if this has been added but please try and make it more noticeable in the user interface

**Comment by pdao1** [comment] 2022-12-13 05:01
I think you have to pay premium to upload images now.

**Comment by kc0tlh** [comment] 2023-08-31 05:31
Closing as a duplicate of #1687. Please follow there for updates!

**Closed by kc0tlh** 2023-08-31 05:31 UTC
