### ISSUE TITLE
Angular 7 with SASS throws "Expected 'styles' to be an array of strings."

### ISSUE THREAD

**Issue by leomendoza123** [stackblitz/core#827] opened 2018-12-23 18:12 UTC
**Steps to replicate**

1- Generate an angular project with Angular CLI (using --style=sass)
2- Upload the project to github and open it with Stackblitz 
3- Add `import 'core-js/es7/reflect'` to `polyfills.ts` (know issue #758)

And the following error is shown 

```
Error in /turbo_modules/@angular/compiler@7.1.4/bundles/compiler.umd.js (9257:23)
Expected 'styles' to be an array of strings.
```

[See it on STACKBLITZ](https://stackblitz.com/github/leomendoza123/angular-architecture-blueprint/tree/d540d9b0ffe586fec7edefecb67a48e4407f0e44)  and [on Github](https://github.com/leomendoza123/angular-architecture-blueprint/tree/d540d9b0ffe586fec7edefecb67a48e4407f0e44)

If I [remove SASS](https://github.com/leomendoza123/angular-architecture-blueprint/commit/4a6d874b9ab02b0133e20a6f4259f4e68bf0df3e), STACKBLITZ is able to open the application 

Tested with @angular/cli 7.1.4 and 7.1.2

**Comment by kajaleprashant24** [comment] 2018-12-28 19:05
I am seeing same issue with project generated with angular-cli with css
https://stackblitz.com/github/kajaleprashant24/angular2App
`Error in /turbo_modules/@angular/compiler@7.1.4/bundles/compiler.umd.js (2497:21)
Can't resolve all parameters for ApplicationModule: (?).`

**Comment by leomendoza123** [comment] 2018-12-28 19:09
> I am seeing same issue with project generated with angular-cli with css
> https://stackblitz.com/github/kajaleprashant24/angular2App
> `Error in /turbo_modules/@angular/compiler@7.1.4/bundles/compiler.umd.js (2497:21) Can't resolve all parameters for ApplicationModule: (?).`

That error is related with #758.

**Comment by kc0tlh** [comment] 2023-08-31 05:49
Closing as duplicate of duplicate of #208. Please follow there for updates!

**Closed by kc0tlh** 2023-08-31 05:49 UTC
Labels: Type: Bug
