### ISSUE TITLE
Unable to edit files

### ISSUE THREAD

**Issue by Saravanan16498** [stackblitz/core#2645] opened 2023-07-20 16:54 UTC
I'm trying to change or modify the files but I can't able to modify.

**Comment by AleksandrSl** [comment] 2023-07-21 07:36
Hi, @Saravanan16498 can you link the project you can't modify and add more details?

**Comment by kc0tlh** [comment] 2023-08-24 17:39
Closing due to lack of reproduction/information.

**Closed by kc0tlh** 2023-08-24 17:39 UTC
