### ISSUE TITLE
file name with hyphen gives an error

### ISSUE THREAD

**Issue by cguldogan** [stackblitz/core#890] opened 2019-03-09 03:10 UTC
When I use a hyphen in the file name like main-test.ts editor redirects me to the following empty page 

https://stackblitz.com/edit/angular-g5zopz?file=src%2Fmain-test.ts

![image](https://user-images.githubusercontent.com/7687931/54065401-859fc700-4218-11e9-948f-eddc2d6c4cfe.png)

**Comment by beeman** [comment] 2019-03-15 19:47
@cguldogan seems to work as expected here:

https://stackblitz.com/edit/angular-vbrlqv?file=src%2Fapp%2Fmy-hyphened-file.ts

Also, you repo does not seem to cause an empty page. Going to close the issue as I can't reproduce it. Feel free to send a link of a Blitz that does fail!

**Closed by beeman** 2019-03-15 19:47 UTC
