### ISSUE TITLE
Can't find package even though package exists in NPM

### ISSUE THREAD

**Issue by transunion-ui** [stackblitz/core#1897] opened 2022-06-13 18:31 UTC
### **Description of Bug**
Can't find package:@transunion-ui/tablejs.

The package exists on NPM, but StackBlitz does not appear to be able to find the requested version (2.1.9).  When I click "install package", it installs version 1.0.0.

Per @markwhitfeld, opening a new issue related to:
#624 https://github.com/stackblitz/core/issues/624#issuecomment-1152983973

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/getting-started-ivy-pzkvlw
2. Attempt to preview the project
3. See that StackBlitz can't find the package.

### **Expected Behavior**
The latest package should install from NPM.

**Comment by scott-cornwell** [comment] 2022-06-16 01:31
I think I'm having the same issue for a little while now. I seem to be able to load old projects that use some of these same dependencies, but if I create a new project and try to add almost any dependency, it can't find it. For instance, go right now and create a new Javascript React project on Stackblitz. Then simply add `styled-components` as a dependency and it can't find it. I also can't remove dependency or the whole screen goes dark, or change the version of dependencies. Site is unusable now :(

**Comment by markwhitfeld** [comment] 2022-06-16 18:59
@transunion-ui your issue is related to the fact that your `package.json` has a `main` field that points to a file that doesn't exist.
See https://www.runpkg.com/?@transunion-ui/tablejs@2.1.9/package.json#12
If you fix the entry points in your package then you should no longer have an issue.
PS. In response to this issue I have added an enhancement to our backlog to disregard entrypoints that reference files that do not exist so that users will still be able to use the older versions of your lib (without the fix to the issue I pointed out above). This enhancement is a bit of a way down the queue though because there are some higher priority fixes we need to get to first.
Please let me know when you have fixed your lib and if it fixes the issue or not.

**Comment by scott-cornwell** [comment] 2022-06-17 03:39
@markwhitfeld Yeah seems fixed now, thanks!

**Comment by transunion-ui** [comment] 2022-06-17 15:46
@markwhitfeld Updating the `main` field seemed to do the trick!  Thanks for your help!

**Comment by markwhitfeld** [comment] 2022-06-17 15:47
Great! Sorry it took so long to get to the bottom of it.
Glad it is all sorted out.

**Closed by markwhitfeld** 2022-06-17 15:47 UTC
Labels: Type: Bug, Status: Triage

**Comment by markwhitfeld** [comment] 2022-09-20 10:58
Hi there. Just to let you know, we have improved our error messaging so that it is easier to detect this type of issue in future.
See my reproduction project: https://stackblitz.com/edit/sb-repro-missing-entrypoint-file-gh-issue-1897
Here is the error message:
![image](https://user-images.githubusercontent.com/1948265/191240750-71c571b2-6774-4423-bcc8-e5404a7241de.png)
