### ISSUE TITLE
Expect to change the console background color

### ISSUE THREAD

**Issue by EnochGao** [stackblitz/core#1474] opened 2021-05-26 08:55 UTC
### **The background color of the console cannot be changed independently.**
The current console user experience is very poor.
now:

![image](https://user-images.githubusercontent.com/41459067/119631847-d96f4880-be42-11eb-8f4f-ee2ea8a4aee4.png)
I found I couldn't make out the output

### **Describe the solution you'd like**

I expect the editor background color to be black and the console background color to be white

**Comment by purplem1lk** [comment] 2021-05-26 14:35
Hello! Thank you for posting this issue - This issue will be closed accordingly as it is a duplicate of #1450 and has already been responded to by one of our StackBlitz devs. Here is a temporary workaround from a user in #1460 while our devs work on this:

> @lovetingyuan you could use
> 
> ```js
>     console.log('%c YOUR_TEXT', 'color:white');
> ```
> 
> till they fix it

If you have any questions, feel free to tag me or continue the conversation in #1450 to keep all conversation/resolution together. Thank you! :)

**Closed by purplem1lk** 2021-05-26 14:35 UTC
Labels: Status: Triage, Type: Feature Request

**Comment by purplem1lk** [comment] 2021-06-08 14:05
Hey @EnochGao, #1450 was updated and the devs have fixed this issue. Feel free to tag me if you are still running into this issue. Thanks!
