### ISSUE TITLE
"The dependencies for this project couldn't be resolved."

### ISSUE THREAD

**Issue by howardchung** [stackblitz/core#370] opened 2018-03-27 08:12 UTC
I attempted to load:
https://stackblitz.com/github/odota/web

This is a create-react-app application.

However, the following error appears:

The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.
If you think this is a bug, please file an issue in our repo!

Is there any additional information about what dependencies might cause this issue?

**Comment by howardchung** [comment] 2018-03-30 03:33
I tested the same repo on codesandbox and it returned an error message saying that there is a limit of 120 modules.  Does stackblitz have a similar limitation?

**Comment by howardchung** [comment] 2018-03-31 04:17
Through trial and error I managed to find the culprit:
https://www.npmjs.com/package/dota2-emoticons

Not sure what's wrong with that package, it's just a bunch of gif files.

I created a fork of the original repo here with that dependency removed:
https://github.com/howardchung/web

Now it encounters the same issue as https://github.com/stackblitz/core/issues/354 where it loads for a while, stalls, then on refresh shows "Something went wrong with this repository."

**Comment by EricSimons** [comment] 2018-04-01 23:16
@howardchung I'm super sorry about my delay here! Thank you so much for providing the detailed error report on this.

To answer your previous q, we don't have any limitations on number of files. I think this may be an issue on our dep resolution side of things. @apai4 and I are going to take a look at the server logs for this tmrw morn and will report back with our findings (and hopefully with a fix :)

**Comment by apai4** [comment] 2018-04-02 23:36
@howardchung the repo you are trying to import is too large, our current limit is ~5mb for all source files (not including node modules and images), yours is about 7mb due to the number of SVG files as we're currently treating them as text files. This should be fixed next month once we release proper asset/image support :+1:

**Comment by howardchung** [comment] 2018-04-03 06:18
Thanks!

I removed the flags from the fork and the editor is able to load the project.  However there are a couple of import errors in the preview pane.

```
Import error, can't find files:
src/components/App/App.js
src/utility.js
```

This is probably a different issue, but it seems specific to StackBlitz since the project builds in a terminal.

https://stackblitz.com/github/howardchung/web

**Comment by seveves** [comment] 2018-04-05 11:11
You could rename all files to `.js` file endings but I think `.jsx` should be also supported (that's why I labelled this issue as a bug).

**Comment by kasparov112000** [comment] 2019-02-12 22:37
any more details about this error, I am getting the same error here is the repo https://github.com/kasparov112000/bio  
https://stackblitz.com/github/kasparov112000/bio

**Comment by joebochill** [comment] 2019-02-15 19:27
I'm having the same error with all react projects. Starting a brand new project with create-react-app and pushing it to github without any modification fails to import with "The dependencies for this project couldn't be resolved."

**Comment by jrohatiner** [comment] 2019-03-10 22:13
same here. the error asks for the react package to be installed and then says "Can't find package:react". The app was working fine and then just errored out. Not sure why. Here is the link: https://stackblitz.com/edit/react-x2sv8b. Thx for any help or advise on this!

**Comment by beeman** [comment] 2019-03-15 19:44
> same here. the error asks for the react package to be installed and then says "Can't find package:react". The app was working fine and then just errored out. Not sure why. Here is the link: [stackblitz.com/edit/react-x2sv8b](https://stackblitz.com/edit/react-x2sv8b). Thx for any help or advise on this!

@jrohatiner in your case it seems like the issue is with the import in `Footer/Footer.js`, if I change `import React from "React";` to `import React from "react";` it works as expected.

**Comment by jaisam** [comment] 2019-08-20 17:31
Can anyone help me out? I'm getting error while importing https://stackblitz.com/github/jaisam/Pokedex repo and getting same error?

**Comment by kenmorechalfant** [comment] 2022-02-20 23:10
I have hit this issue on 2 React projects now. If indeed it is because of the size it would be helpful to at least tell the user that. 5MB sounds reasonable but unfortunately a fresh `create-react-app` Typescript project is 287MB as of this writing.

**Comment by kc0tlh** [comment] 2023-08-24 23:37
As far as I can tell this issue is now resolved for all repos in this thread. If issue is still persisting for any of you, please open a fresh issue with your repro link, tag me, and we can work on it there!

**Closed by kc0tlh** 2023-08-24 23:37 UTC
Labels: Type: Bug
