### ISSUE TITLE
JavaScript -Generator  (for loop) -- not-working in Stackblitz

### ISSUE THREAD

**Issue by jagadeeshtechgeek** [stackblitz/core#403] opened 2018-04-11 21:22 UTC
https://stackblitz.com/edit/generator-for-loop-not-working?file=index.js

```js
function *listFn() {
  yield 1;
  yield 2;
  yield 3;
  yield 4;
}

const listGenerator = listFn();
const values= [];
for (let val of listGenerator) {
  values.push(val);
}
console.log(values);  // not working
```

same code works in **Google Chrome** Console

**Comment by seveves** [comment] 2018-04-12 07:59
Duplicate of #353?

**Comment by jagadeeshtechgeek** [comment] 2018-04-12 17:31
Yes

**Comment by seveves** [comment] 2018-04-13 06:26
So let's track the progress over there and close this. Thank you for reporting the issue anyway 😄

**Closed by seveves** 2018-04-13 06:26 UTC
Labels: duplicate
