### ISSUE TITLE
Pressing Ctrl+P ? crashes the web app

### ISSUE THREAD

**Issue by ghost** [stackblitz/core#716] opened 2018-10-03 21:16 UTC
## Steps to reproduce:

1. Open any Stackblitz workspac (e.g. https://stackblitz.com/edit/js)
2. Press **Ctrl+P**
3. Press **?**

## Results:

* Stackblitz webapp goes blank. Won't work again unless refreshed.
* JS console shows error `SyntaxError: Invalid regular expression: /?/: Nothing to repeat`.

Js console log:

```
client-3a954afa5f621fbf3223a.js:1 SyntaxError: Invalid regular expression: /?/: Nothing to repeat
    at new RegExp (<anonymous>)
    at client-3a954afa5f621fbf3223a.js:1
    at Ze (ext-1b04efca0f6e14ddf11da.js:1)
    at Function.yr.filter (ext-1b04efca0f6e14ddf11da.js:1)
    at t.e.getSearchResults (client-3a954afa5f621fbf3223a.js:1)
    at t.value (client-3a954afa5f621fbf3223a.js:1)
    at Ai (client-3a954afa5f621fbf3223a.js:1)
    at Di (client-3a954afa5f621fbf3223a.js:1)
    at pa (client-3a954afa5f621fbf3223a.js:1)
    at ha (client-3a954afa5f621fbf3223a.js:1)
    at Ya (client-3a954afa5f621fbf3223a.js:1)
    at Ka (client-3a954afa5f621fbf3223a.js:1)
    at fs (client-3a954afa5f621fbf3223a.js:1)
    at Xe (client-3a954afa5f621fbf3223a.js:1)
    at Nn (client-3a954afa5f621fbf3223a.js:1)
    at ns (client-3a954afa5f621fbf3223a.js:1)
zi @ client-3a954afa5f621fbf3223a.js:1
Ki.n.callback @ client-3a954afa5f621fbf3223a.js:1
Wo @ client-3a954afa5f621fbf3223a.js:1
qo @ client-3a954afa5f621fbf3223a.js:1
Ja @ client-3a954afa5f621fbf3223a.js:1
Ya @ client-3a954afa5f621fbf3223a.js:1
Ka @ client-3a954afa5f621fbf3223a.js:1
fs @ client-3a954afa5f621fbf3223a.js:1
Xe @ client-3a954afa5f621fbf3223a.js:1
Nn @ client-3a954afa5f621fbf3223a.js:1
ns @ client-3a954afa5f621fbf3223a.js:1
Dn @ client-3a954afa5f621fbf3223a.js:1
client-3a954afa5f621fbf3223a.js:1 Uncaught SyntaxError: Invalid regular expression: /?/: Nothing to repeat
    at new RegExp (<anonymous>)
    at client-3a954afa5f621fbf3223a.js:1
    at Ze (ext-1b04efca0f6e14ddf11da.js:1)
    at Function.yr.filter (ext-1b04efca0f6e14ddf11da.js:1)
    at t.e.getSearchResults (client-3a954afa5f621fbf3223a.js:1)
    at t.value (client-3a954afa5f621fbf3223a.js:1)
    at Ai (client-3a954afa5f621fbf3223a.js:1)
    at Di (client-3a954afa5f621fbf3223a.js:1)
    at pa (client-3a954afa5f621fbf3223a.js:1)
    at ha (client-3a954afa5f621fbf3223a.js:1)
    at Ya (client-3a954afa5f621fbf3223a.js:1)
    at Ka (client-3a954afa5f621fbf3223a.js:1)
    at fs (client-3a954afa5f621fbf3223a.js:1)
    at Xe (client-3a954afa5f621fbf3223a.js:1)
    at Nn (client-3a954afa5f621fbf3223a.js:1)
    at ns (client-3a954afa5f621fbf3223a.js:1)
(anonymous) @ client-3a954afa5f621fbf3223a.js:1
Ze @ ext-1b04efca0f6e14ddf11da.js:1
yr.filter @ ext-1b04efca0f6e14ddf11da.js:1
e.getSearchResults @ client-3a954afa5f621fbf3223a.js:1
value @ client-3a954afa5f621fbf3223a.js:1
Ai @ client-3a954afa5f621fbf3223a.js:1
Di @ client-3a954afa5f621fbf3223a.js:1
pa @ client-3a954afa5f621fbf3223a.js:1
ha @ client-3a954afa5f621fbf3223a.js:1
Ya @ client-3a954afa5f621fbf3223a.js:1
Ka @ client-3a954afa5f621fbf3223a.js:1
fs @ client-3a954afa5f621fbf3223a.js:1
Xe @ client-3a954afa5f621fbf3223a.js:1
Nn @ client-3a954afa5f621fbf3223a.js:1
ns @ client-3a954afa5f621fbf3223a.js:1
Dn @ client-3a954afa5f621fbf3223a.js:1
```

**Comment by linhub15** [comment] 2018-10-23 17:01
In addition to the question mark character `?` the following also cause the same issue
Left Parenthesis `(`
Right Parenthesis `)`
Left Square Bracket `[`
Reverse Solidus `\`
Asterisk `*`

**Comment by purplem1lk** [comment] 2021-04-27 13:59
Thank you for your patience - I'm unable to reproduce this myself. It's possible that this issue was resolved through other code changes over time. I will be closing this issue, but if your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)

**Closed by purplem1lk** 2021-04-27 13:59 UTC
Labels: bug
