### ISSUE TITLE
turbo_modules/@taiga-ui/core@2.41.0/styles/theme/wrapper.less

### ISSUE THREAD

**Issue by splincode** [stackblitz/core#1828] opened 2022-04-11 18:34 UTC
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Steps to Reproduce**

1. Go to https://taiga-ui.dev/components/avatar
2. Click on 'Edit on stackblitz'
3. See error

<img width="555" alt="image" src="https://user-images.githubusercontent.com/12021443/162806360-2f7df811-12e1-419c-919b-bf2840f92791.png">

```
Error in turbo_modules/@taiga-ui/core@2.41.0/styles/theme/wrapper.less (10:0)
Could not import ./wrapper/base.less from /turbo_modules/@taiga-ui/core@2.41.0/styles/theme/wrapper.less
```

### **Expected Behavior**

Works

**Comment by markwhitfeld** [comment] 2022-04-27 14:03
This is potentially related to changes in the path resolution with ESM style packages.
This has been resolved for SASS. I will add this to my backlog to investigate.

**Comment by waterplea** [comment] 2022-10-14 08:37
@markwhitfeld are there any news on that?

**Comment by markwhitfeld** [comment] 2023-01-05 12:25
I am battling to reproduce the issue from the docs page, but it looks like there is a decent repro on issue #2112.
Busy investigating....

**Comment by markwhitfeld** [comment] 2023-01-05 20:01
The fix is approved and is on its way. Our deployment pipeline is just on hold at the moment with tokens being replaced in light of the CircleCI security alert.

**Comment by markwhitfeld** [comment] 2023-01-06 16:10
The fix has been deployed. Closing this. Let us know if you experience the same issue again.

**Closed by markwhitfeld** 2023-01-06 16:10 UTC
Labels: Type: Bug, Status: Triage
