### ISSUE TITLE
Can't Find Package after updating in NPM

### ISSUE THREAD

**Issue by andrew-frueh** [stackblitz/core#1903] opened 2022-06-20 22:33 UTC
### **Description of Bug**
Many thanks to @markwhitfeld for the followup on #624 related to this issue.  We've been using Stackblitz for quite some time as a way for our developers to edit the examples in our design system at: 
https://cashmere.healthcatalyst.net/web/components

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/angular-suepzj
2. Let the project attempt to load and compile
3. See error in right panel - "Can't find package: `@healthcatalyst/cashmere`"

**Additional Context/Questions**
Version 13.0.0 does exist on NPM and can be pulled in to applications:
https://www.npmjs.com/package/@healthcatalyst/cashmere

It might be worth noting that on line 28 of package.json we are using the following syntax to import Cashmere:
`"@healthcatalyst/cashmere": "*"`
I'm not sure if using a star is causing a problem for Stackblitz.  It's worked in the past, but maybe something changed with this release?  Also worth noting that if I change line 28 to:
`"@healthcatalyst/cashmere": "12.8.1"`
...then Stackblitz loads the package correctly.  So it's just something that's turned up with this v13 release.  Lucky 13 :-)

**Comment by andrew-frueh** [comment] 2022-07-13 16:16
Hi all, just bumping this request.  We recently pushed a new version of our library, version 13.1.0, and I was hoping might update the npm package for Stackblitz.  But we're still seeing the same error, any version after 12.8.1 can't seem to be found.  Would appreciate any help or suggestions.  Thanks!

**Comment by corykon** [comment] 2022-08-22 22:39
@markwhitfeld is this still something on your radar? are there other channels you recommend we reach out for support?

**Comment by markwhitfeld** [comment] 2022-08-23 08:52
Hi @andrew-frueh and @corykon 
I somehow missed this notification. I had a quick look, and it seems that there is an issue in the `package.json` since the v13.0.0 release of `@healthcatalyst/cashmere`.
The `main` field of the `package.json` refers to a file `/bundles/cashmere.umd.js` which is not included in the package.
The StackBlitz project is failing when it follows the `main` entrypoint and the file does not exist. 
I will add an issue into the backlog to try to improve the error message, because the current failure is a bit confusing.
You can see the issue with the entrypoint using runpkg here:
https://www.runpkg.com/?@healthcatalyst/cashmere@13.2.0
https://www.runpkg.com/?@healthcatalyst/cashmere@13.0.0
See: https://www.runpkg.com/?@healthcatalyst/cashmere@13.2.0/package.json#13
(haha, an unlucky line 13 too 😉 )

And it works in the last v12 version:
https://www.runpkg.com/?@healthcatalyst/cashmere@12.8.1

I will close this issue, and the internal task I mentioned.

**Closed by markwhitfeld** 2022-08-23 08:52 UTC
Labels: Type: Question, Status: Done

**Comment by andrew-frueh** [comment] 2022-08-23 18:32
Thanks so much for digging into this for us @markwhitfeld!  That's exactly what we needed to know.  We'll work on a fix from our end.

**Comment by markwhitfeld** [comment] 2022-09-20 10:59
Hi there. Just to let you know, we have improved our error messaging so that it is easier to detect this type of issue in future.
See my reproduction project: https://stackblitz.com/edit/sb-repro-angular-entrypoint-failure-message
Here is the error message:
![image](https://user-images.githubusercontent.com/1948265/191240899-f93ab84b-faec-4cfc-b6fc-1b2b36686617.png)

**Comment by corykon** [comment] 2022-09-20 16:43
@markwhitfeld That's awesome! Super helpful. Thank you.
