### ISSUE TITLE
Images won't load in PIXI

### ISSUE THREAD

**Issue by jrvidal** [stackblitz/core#1813] opened 2022-03-28 07:47 UTC
I'm seeing this too. In my case I'm trying to set up a PIXI.js sandbox.
Project url is https://stackblitz.com/edit/mikesimons-pixi-play

PIXI is trying to load https://mikesimons-pixi-play.stackblitz.io/assets/character.png but if you open that url in a tab you get the HTML from the project, not the image.

_Originally posted by @mikesimons in https://github.com/stackblitz/webcontainer-core/issues/627#issuecomment-1079968318_

**Comment by kc0tlh** [comment] 2023-08-31 05:31
Closing as a duplicate of #1687. Please follow there for updates!

**Closed by kc0tlh** 2023-08-31 05:31 UTC
