### ISSUE TITLE
i get exception for my app on stackBlitz but actual runnig app is working on my localhost

### ISSUE THREAD

**Issue by msalehisedeh** [stackblitz/core#374] opened 2018-03-29 04:27 UTC
Can you give me a pointer on what i can do to resolve this?

Error: StaticInjectorError(AppModule)[TagComponent -> Renderer]: 
  StaticInjectorError(Platform: core)[TagComponent -> Renderer]: 
    NullInjectorError: No provider for Renderer!
Stack trace:
_NullInjector.prototype.get@https://tagbox.stackblitz.io/turbo_modules/@angular/core@5.2.8/bundles/core.umd.js:1040:19

**Comment by msalehisedeh** [comment] 2018-03-29 04:31
on a different application get a different error
Error: StaticInjectorError(AppModule)[NgForOf -> ViewContainerRef]: 
  StaticInjectorError(Platform: core)[NgForOf -> ViewContainerRef]: 
    NullInjectorError: No provider for ViewContainerRef!
Stack trace:
_NullInjector.prototype.get@https://diffrenciate.stackblitz.io/turbo_modules/@angular/core@5.2.8/bundles/core.umd.js:1040:19

please help

**Comment by seveves** [comment] 2018-03-29 05:57
May you provide your stackblitz project?

**Comment by msalehisedeh** [comment] 2018-03-29 06:32
https://stackblitz.com/edit/tagbox

https://stackblitz.com/edit/diffrenciate

**Comment by seveves** [comment] 2018-03-29 10:01
hm your modules are also working when I'm running them locally with angular-cli ... so it looks like the turbo is loading the angular module differently. Consuming my own library (like ngx-scroll-viewport) works perfectly but this one was not created with ng-packagr. So maybe it is related to the way how ng-packagr is bundling the library.
I'll try to find another library using ng-packagr to test it out.

**Comment by seveves** [comment] 2018-03-29 10:10
Ok I've tested with ngx-paginate which is also created with ng-packagr and there we have the same issues:
https://stackblitz.com/edit/angular-wbggyw?file=app%2Fapp.module.ts

**Comment by seveves** [comment] 2018-03-29 10:28
When doing something crazy like importing the package via unpkg.com (f.e. `import { NgxPaginateModule } from 'https://unpkg.com/ngx-paginate@1.0.5/ngx-paginate.es5.js';`) then it works.

You can see your working tagbox project [here](https://stackblitz.com/edit/tagbox-sglhje?file=app/app.component.ts).

Now it's on to @EricSimons and @apai4 ... I'm done with my research 👓

**Comment by msalehisedeh** [comment] 2018-03-29 14:02
Thank you very much.. appreciate it.. i tried to use your example to resove font-awesome problem.. but i get file not found when i use https://unpkg.com/font-awesome@4.7.0/css/font-awesome.min.css in the main style.css file... how that can be resolved... i am extremely appreciative of your help. Best regards - Masoud

**Comment by seveves** [comment] 2018-03-31 06:04
Can't you add font-awesome as a external dependency instead of a npm package?

**Comment by msalehisedeh** [comment] 2018-04-01 08:29
how can i do it? considering the package i created depends on font-awesome.

**Comment by seveves** [comment] 2018-04-05 08:29
you can add external dependencies below the file explorer right under "npm dependencies". There you can add scripts or css files. It's worth a try ... if it's not working then please link your updates project and I will take a look at it 😄

**Comment by msalehisedeh** [comment] 2018-04-05 14:02
Thanks.. font-awesome problem is fixed... you are awesome ;-)

**Comment by msalehisedeh** [comment] 2018-04-07 09:38
Need one more help...
Have a new application "https://stackblitz.com/edit/visualization-points".... it needs to load a js file as asset.. i have updated the angular-cli file but looks like it is not picking it up and i get error... appreciate your help..

**Comment by msalehisedeh** [comment] 2018-04-08 04:53
based on what i have found on internet, looks like i get this error because the link is redirected to html... and this sounds just about right because when i type it on the browser url field, i get redirected... i tried to use the git hub as a source for the js file, but the link i used was also delivering text/html... now the question is if i should make the file external dependency or import it in a different way..

**Comment by msalehisedeh** [comment] 2018-04-08 05:09
now when i do this on my localhost "http://localhost:4200/assets/d3.js" there is no issue... **what can i do for the stackblitz.io to allow serving the resource and not redirecting me to my application?**

**Comment by msalehisedeh** [comment] 2018-04-08 07:56
never mind.. I did external dependency with the source file on git hub
https://raw.githubusercontent.com/msalehisedeh/visualization-points/master/dist/assets/d3.js

I was expressing my thoughts out laud.. thanks for listening..

**Comment by msalehisedeh** [comment] 2018-04-10 00:07
HELP!!!!! HELP!!!! Looks like the external resource thing only works on Mozilla... both IE and chrome are failing on the d3.js file i am referencing.. or the js is not loading in advance before my internal code trying to load the js...
what is the remedy to this..?

**Comment by msalehisedeh** [comment] 2018-04-10 00:47
OK.. the solution is on https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github
turned out i have to change the url to
https://cdn.rawgit.com/msalehisedeh/visualization-points/master/dist/assets/d3.js

**Comment by seveves** [comment] 2018-04-12 09:04
so everything works now?

**Comment by msalehisedeh** [comment] 2018-04-13 05:02
for this particular application.. YES... however, the application i had trouble with and mentioned way way above.. https://stackblitz.com/edit/differentiate  --  i still have problem to fix.. it turns out if i have any injection in directive construction, stackblitz is not able to handle it and i get null injection exception... if you can find a solution for it, i will be grateful...

**Comment by msalehisedeh** [comment] 2018-04-14 02:06
Thanks.. Is it possible to direct me to another way of compiling and deploying on npm? While back, i got a process from internet and i was getting some sort of exception... i thought it is because i am on Windows OS. As a result i switched to ng-packagr... If you know another way of compiling and deploying to npm, please let me know... I think some of beneficiaries of my applications may not be able to use them as a result of being involved with ng-packagr...  i appreciate any directions that leads me to the finish line!!

**Comment by seveves** [comment] 2018-04-16 07:57
I'm sorry but I think you should ask this question over at the ng-packagr project. I'm sure they can help you way better. Feel free to link this issue so they see what's not working.

**Comment by msalehisedeh** [comment] 2019-02-07 14:13
I started to scope my projects and for the most part i do not have to use unpkg.com anymore. But, for one of my projects @sedeh/visualize-it, I get Static injection no provider message for Renderer2. When I try to inject Renderer2 within the app root, i get the same error message at root level for AppComponent which tells me the problem is not in visualize-it module.  How can i make stackblitz provide Renderer2?

**Comment by msalehisedeh** [comment] 2019-02-08 05:13
I tried to build a totally new stackblitz project and dropped code in it. But it did not make any difference. then i updated my component on npm to inject rendererfactory and create the renderer instead. Now i get the same no provider static injection error but instead on the rendererfactory.

**Comment by sulco** [comment] 2021-01-28 16:08
Closing, as it seems the issue is resolved. Please free to reopen if that is actually not the case.

**Closed by sulco** 2021-01-28 16:08 UTC
Labels: potential bug
