### ISSUE TITLE
Upgrade turbo tracer to aggressively cache type-related assets 

### ISSUE THREAD

**Issue by kylecordes** [stackblitz/core#386] opened 2018-04-03 16:40 UTC
It looks like the StackBlitz magic-behind-the-scenes is not yet compatible with the new rxjs forward-compat versions. This example shows the problem:

https://stackblitz.com/github/AngularBootCamp/filtered-list-via-observable?file=src%2Fapp%2Femployee-list%2Femployee-list.component.ts

It does not recognize rxjs/operators:

![screen shot 2018-04-03 at 11 34 54 am](https://user-images.githubusercontent.com/8799/38262640-782f944c-3733-11e8-9500-5728d01f931d.png)

rxjs/operators *is* recognized with the slightly older 5.5.6 version, just not with `rxjs@5.6.0-forward-compat.2`

I don't have a test in front of me with rxjs@6; expect both variance to be around for a while so probably should be tweaked to work.

**Comment by EricSimons** [comment] 2018-04-03 16:51
Errgh yeah this is related to https://github.com/stackblitz/core/issues/229. The code will actually work perfectly, the problem is just around tracing type definitions/etc (hence the red underline, as it can't find them).

We have a fix for this that should solve it, will get it prioritized & report back once it's live. Thanks for reporting this sir! 🍻

**Comment by purplem1lk** [comment] 2021-04-30 20:09
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Closed by purplem1lk** 2021-04-30 20:09 UTC
Labels: bug, on deck
