### ISSUE TITLE
Editor doesn't work with virtual keyboards on Android devices

### ISSUE THREAD

**Issue by zcdunn** [stackblitz/core#349] opened 2018-03-16 22:32 UTC
When using different keyboards on different Android devices, the editor can't handle input properly. It seems to insert weirdly broken versions of what I typed and backspace doesn't work. 

I've observed this on:
* Nexus 7 gen2
   + Android 6.0.1
   + Firefox 59.0.1
   + GBoard keyboard
* Nexus 5x
   + Android 7.1.2
   + Firefox 59.0.1
   + Minuum keyboard

**Comment by EricSimons** [comment] 2018-03-22 03:20
Yeah this is an upstream issue with VS Code's Monaco editor itself unfortunately :/ Will see what we can do on this front to fix though.

**Comment by AlteredCarbonate** [comment] 2020-12-13 14:25
### **Push**

The issue is still there!

- HUAWEI MatePad T10s
   - Android 10
   - EMUI 10.1
   - Google Chrome
   - Default Keyboard

- HUAWEI P20 Pro
   - Android 10
   - EMUI 10
   - Google Chrome
   - Default Keyboard

Every action doesn't work.

- Selecting
- Removing
- Code Completion

Please fix it... I would love to use it on the Go!

**Comment by SamVerschueren** [comment] 2021-04-08 19:58
We can't do much about it tbqh. It's a editor issue. We use Monaco. I tried it on my iPhone and it works properly.

Closing this as I believe it's an upstream issue. Feel free to open an issue in the monaco repository https://microsoft.github.io/monaco-editor/.

Try using your phone for the typescript playground https://www.typescriptlang.org/play and see if you experience the same issue. I think it should.

**Closed by SamVerschueren** 2021-04-08 19:58 UTC
Labels: bug
