### ISSUE TITLE
How to run npm scripts

### ISSUE THREAD

**Issue by rupeshtiwari** [stackblitz/core#600] opened 2018-07-13 02:36 UTC
Hi I want to use https://www.npmjs.com/package/json-server npm package. Which will help me to create api endpoint. It needs to run `json-server --watch db.json` script in order to run this server which will give us and endpoint `http://localhost:3000/posts/1,` 
Question is how can I run above npm script ?

**Comment by chan-dev** [comment] 2019-07-20 19:29
any updates on this one?

**Comment by d3lm** [comment] 2019-07-27 09:31
As of right now one can not run npm scripts or node packages, but we are working on something that will allow you to do exactly that inside the browser. We'll keep you posted.

**Comment by Lacarte** [comment] 2020-07-02 12:37
Any update please?

**Comment by chromyd** [comment] 2020-11-06 15:50
This would be a cool feature. We plan to use stackblitz for an online training and we'd love to be able to run lint and prettier via npm script. Would that be possible and if yes, do you have an ETA for the feature?

**Comment by hiteshboricha** [comment] 2021-06-16 07:06
Is this still open, I too am trying to run json-server iva stackblitz

**Comment by chromyd** [comment] 2021-06-16 07:57
Hey I think the feature that @d3lm mentioned is this one: https://blog.stackblitz.com/posts/introducing-webcontainers/

So now it is possible to create a Node.js project in StackBlitz and indeed run the scripts specified in package.json.

**Comment by d3lm** [comment] 2021-06-16 08:03
@Lacarte @chromyd Yes exactly. We have launched WebContainers and it's a Node.js runtime for the browser which allows you to run npm scripts and do much more than that.

Thanks for linking the blog post!

So if you want a Node project, install dependencies with npm or yarn, run npm scripts you have to use the [Node.js starter template](https://stackblitz.com/fork/node).

**Comment by fvsch** [comment] 2022-06-29 12:51
Hi everyone. I’m closing this question / feature request, because the WebContainers / Node.js project type we launched in beta in 2021 and as a stable feature in 2022 is our answer to this need. Cheers!

**Closed by fvsch** 2022-06-29 12:51 UTC
Labels: Type: Feature Request, Status: Done

**Comment by Alexander-Stulov** [comment] 2024-01-06 04:17
Size issue is related to **@wagmi/connectors** (core, without react)
Link to sample project:
https://stackblitz.com/edit/vitejs-vite-bbzuv4?file=vite.config.ts

Steps to reproduce: 
1. Download sample project (the only logic it has is to connect to MetaMask wallet, image 1)
2. Run npm run build (it prepares production-ready build). Stackblitz doesn't have this option
3. Produced file size:  1,703.50 kb (image 2)
4. If I exclude @wagmi/connectors (image 3), the file size drops to 103.56 kb (image 4). **Diff: 1,599.94 kb**
<img width="425" alt="image 1" src="https://github.com/stackblitz/core/assets/2744160/9e2a533d-3121-4ca1-9028-f4457bf972f5">
<img width="502" alt="image 2" src="https://github.com/stackblitz/core/assets/2744160/1f31eac2-25e0-4d52-bda5-3f0c074d3c4c">
<img width="609" alt="image 3" src="https://github.com/stackblitz/core/assets/2744160/3bb78763-4d02-4583-a84b-728e679e3cca">
<img width="453" alt="image 4" src="https://github.com/stackblitz/core/assets/2744160/8a543140-8d6a-4880-9ef2-4ae7597c358f">

The previous version @wagmi/core 1.4.12 doesn't have such an issue. Please advise.
