### ISSUE TITLE
There is a problem with uploading an image, the editor can't "read" it.

### ISSUE THREAD

**Issue by Croc-Prog-github** [stackblitz/core#2528] opened 2023-05-20 09:33 UTC
When in the Stackblitz editor I load an image (by connecting the project to a GitHub Repository and then from GitHub I load an image from the PC files, when on Stackblitz I update the files [importing them from GitHub]), the image file ( on Stackblitz) there is; but the image is not materially there. I'm keeping trying different ways. I hope you can solve this problem.

**Comment by kc0tlh** [comment] 2023-08-31 05:30
Closing as a duplicate of #1687. Please follow there for updates!

**Closed by kc0tlh** 2023-08-31 05:30 UTC
