### ISSUE TITLE
Can't find module, not able to import

### ISSUE THREAD

**Issue by shyamal890** [stackblitz/core#307] opened 2018-02-26 16:56 UTC
https://stackblitz.com/edit/angular-medium-editor

**Comment by seveves** [comment] 2018-02-27 20:36
you are using [angular-medium-editor](https://github.com/thijsw/angular-medium-editor) right?
This is an angularJS (angular 1.x) library and does not work with the angular 2+ template.

you must use another library. F.e. https://github.com/codiak/angular2-medium-editor

**Comment by shyamal890** [comment] 2018-02-27 20:40
angular-medium-editor has a alpha release v4.0.0 for angular 2+

**Comment by seveves** [comment] 2018-02-27 20:52
when looking at the package import via [unpkg](https://unpkg.com/angular-medium-editor@4.0.0-alpha/medium-editor.directive.ts) it looks like they don't export a valid ES module or sth. else and that is what the import is expecting.

They should provide UMD, AMD, fesm etc. modules but that's another story ... I would copy the code of the medium-editor.directive.ts to a local stackblitz file and use it directly.

**Comment by shyamal890** [comment] 2018-02-27 20:55
Still doesn't work https://stackblitz.com/edit/angular-medium-editor-custom-import

**Comment by seveves** [comment] 2018-02-27 21:02
Removed the '.ts' file extension and the import worked fine for me (blank page with 'undefined' was the result)

**Comment by sulco** [comment] 2021-01-28 15:56
Closing, as it seems the issue is resolved. Please free to reopen if that is actually not the case.

**Closed by sulco** 2021-01-28 15:56 UTC

**Comment by peter-duong-tgl** [comment] 2021-06-15 05:56
Got the same issue. I had to refresh the page. Please fix.
