### ISSUE TITLE
SVG support in assets

### ISSUE THREAD

**Issue by BigBadaboom** [stackblitz/core#1512] opened 2021-06-21 14:35 UTC
I'm trying to use an SVG file in my project.

It actuall gets served if I put it in the `assets` folder. Unfortunately it is being served as `text/html`.  It needs to be `image/svg+xml`  :/

**Comment by kc0tlh** [comment] 2023-08-31 06:19
Closing as duplicate of #1687

**Closed by kc0tlh** 2023-08-31 06:19 UTC
Labels: Type: Bug, Status: Triage
