### ISSUE TITLE
Missing LICENSE files

### ISSUE THREAD

**Issue by wmhilton** [stackblitz/core#418] opened 2018-04-19 03:04 UTC
So... it's not really open source?!!

**Comment by seveves** [comment] 2018-04-20 05:42
It is new and fresh and maybe they don't know where this is going so at the moment I don't think you can call stackblitz 100% open source. But maybe they want to reach some stable point (code quality and not only having many features) before they make it fully open source. There are many issues at the moment and I don't think it would be helpful to have the same amount of pull requests when you are heavily developing.
So for now you have to be patient 😄 

Duplicate of #327

**Comment by goldingdamien** [comment] 2018-08-18 08:15
This is quite a big issue. Would be nice if some official information on this was provided.
Even if it is not ready for an open source license if they could state something such as "it is copyrighted for now until further notice" it would create some clarity on the matter.

Regards.

**Comment by wmhilton** [comment] 2018-08-19 02:04
I just feel is disingenuous to host the source code publicly on Github and not have an open source license.

**Comment by mike-north** [comment] 2018-08-20 18:46
> There are many issues at the moment and I don't think it would be helpful to have the same amount of pull requests when you are heavily developing.

Applying a license does not require you to accept incoming patches

**Comment by EricSimons** [comment] 2018-08-20 19:38
Hey all, sorry about the delay here. We're a small 2 man team and are continuously flooded with high priority fixes & updates, so this has been a low prio issue on our end but I totally understand why folks are seeking resolution.

The StackBlitz SDK is fully MIT, but for Turbo we're still in the process of determining which license to use due to contractual obligations on our end. In the interim, feel free to use Turbo under the [GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html) license.

Also, big thanks to @seveves for chiming in & helping answer these q's- we really appreciate your help sir ❤️

**Comment by wmhilton** [comment] 2018-08-20 19:59
Hey Eric, I'll make it super easy for ya! #653 and #654 👍

**Comment by dummy-account-vidyo** [comment] 2018-12-11 14:57
Hi all i have one query regarding stackblitz online ide i want to use that ide in my project do i need to take any kind of licene for it or i can use it freely like i use sdk.

**Comment by AbhinavAtul** [comment] 2020-10-26 20:42
[**You may not modify, reproduce, republish, frame, download, transmit, distribute, rent, lease, loan, sell, assign, license, sublicense, reverse engineer, publicly display or create derivative works based on the Services, any of StackBlitz's Content in whole or in part, or the Site except as expressly authorized in writing by StackBlitz.**](https://stackblitz.com/terms-of-service)


Does this mean if you are learning some angular concepts on StackBlitz, you are not supposed to *create derivative works* for your own software, lol, I would appreciate if this is included in all code files as the © copyright/license notice cc @EricSimons

**Comment by AbhinavAtul** [comment] 2020-10-26 20:47
thank you stack blitz, i will not visit you anymore until you plan to have a **Creative Commons license**

**Comment by purplem1lk** [comment] 2021-09-29 21:28
The core repository has been updated with the MIT license notice: master/LICENSE

Feel free to tag me if you have any questions, thank you!

**Closed by purplem1lk** 2021-09-29 21:28 UTC
Labels: Type: Duplicate
