### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by krishnatandon1208** [stackblitz/core#1369] opened 2021-01-25 03:30 UTC
![Screenshot 1942-11-05 at 08 59 36](https://user-images.githubusercontent.com/58399691/105658030-a98f5300-5eeb-11eb-9ff8-3447d22fea3d.png)

This error occurs when trying to login using Github

**Comment by katopz** [comment] 2021-02-06 04:11
Same here

**Comment by pattaraprach** [comment] 2021-02-06 04:25
Same here. Can't Login

**Comment by loumacdev** [comment] 2021-02-06 12:08
same issue - same error

**Comment by johnhowze** [comment] 2021-02-06 17:28
Same thing - two different PCs... Help! please...

**Comment by Find-Me-Ariadne** [comment] 2021-02-06 22:06
Same here, help would be much appreciated!

**Comment by cqlin** [comment] 2021-02-07 01:04
Same error.  Tried all browsers: Chrome, Firefox, Edge, Safari

**Comment by toviszsolt** [comment] 2021-02-07 02:13
Yikes! Something went wrong with your request.
If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core

**Comment by toviszsolt** [comment] 2021-02-07 02:27
**Looks like this project is dead... But I wanted to register.**
Another issue opened 28 days ago -> https://github.com/stackblitz/core/issues/1360
This issue opened 13 days ago -> https://github.com/stackblitz/core/issues/1369
Last commit Sep 25 2020 -> https://github.com/stackblitz/core/commit/7d05daade9c376eae782f0cd71be7cae6182b8c8
@EricSimons @apai4 where are you guys?

**Comment by EricSimons** [comment] 2021-02-07 02:54
Not dead! This has been difficult to repro on our end. I’m having our team take a look Monday and will circle back here with the latest.

**Comment by toviszsolt** [comment] 2021-02-07 03:03
@EricSimons if it help you guys: 
- I never used stackblitz earlier, so maybe problem with register or maybe GitHub changed something in Auth API.
- I tried in Incognito mode also. Deleted cookies and Application Stirage, not helped.

If I can help something, just tell me.

**Comment by sulco** [comment] 2021-02-07 19:10
Hey everyone! I'm sorry you're experiencing these issues. A tiny piece of good news is that I've finally been able to reproduce this issue (I'm on the team), so we should be much closer to fixing this. 

This issue is a priority for us right now, so we will give an update on Monday, in either way, whether the fix is ready, or we're still working on it.

**Comment by KennyRay549** [comment] 2021-02-08 16:11
Following this issue ... from #1385

**Comment by sulco** [comment] 2021-02-08 20:08
Hey! We have pushed an update that should help with the issue some of you are having - can you try logging in again?

**Comment by cqlin** [comment] 2021-02-08 23:41
After the recent update, login works fine now.  Thanks!

**Comment by loumacdev** [comment] 2021-02-09 07:46
I can now login after the update too, many thanks!

**Comment by toviszsolt** [comment] 2021-02-09 13:57
> Hey! We have pushed an update that should help with the issue some of you are having - can you try logging in again?

@sulco I can confirm: **It works fro me**

**Comment by sulco** [comment] 2021-02-12 11:15
Great to hear that!

I'm closing the issue then :) (please free to reopen if you still experience the issue though!)

**Closed by sulco** 2021-02-12 11:15 UTC
Labels: bug
