### ISSUE TITLE
Not able to modify the minutes selector in PrimeNG calender 

### ISSUE THREAD

**Issue by raysmarak** [stackblitz/core#869] opened 2019-02-14 06:18 UTC
Hi,

Unable to modify(increase/decrease) the minute section in PrimeNG calender even in the latest version. 
Steps to reproduce:-
1> Take 2 p-calender (one for From date and other for To Date)
2> We have added one condition in the To date that it should be less than From date
3> Select From and To dates to same date
4> Let From date time be XX hrs :50 mins
5> Now, To date minutes cannot go less than 50, even though the hours is set more than XX hours.
6> But if you manually type the minutes, say 26, the minute scroll freezes.
Can someone please fix the same.

Br,
Smarak

**Comment by sulco** [comment] 2021-01-28 12:55
Hi @raysmarak, thanks for posting the issue. Since it does not seem to be related to the StackBlitz platform, I'm closing it for now.

Feel free to reopen if you believe that's not the case. Adding the link to the project with reproduction would be a huge help too!

**Closed by sulco** 2021-01-28 12:55 UTC
