### ISSUE TITLE
StackBlitz SDK do not install dependencies

### ISSUE THREAD

**Issue by nsbarsukov** [stackblitz/core#2166] opened 2022-11-17 10:16 UTC
### **Description of Bug**
We actively use [Stackblitz SDK](https://developer.stackblitz.com/platform/api/javascript-sdk) for a long time.
But recently it stopped installing requested dependencies after [sdk.openProject](https://developer.stackblitz.com/platform/api/javascript-sdk#openproject)-command.

### **Steps to Reproduce**
1. Open this HTML-file in browser

<details>
<summary><strong>HTML-file starter with NO bug</strong></summary>

```html
<script type="module">
    import sdk from 'https://unpkg.com/@stackblitz/sdk@1/bundles/sdk.m.js';

    sdk.openProject(
        {
            title: `Taiga UI Starter`,
            template: `angular-cli`,
            dependencies: {
                "@angular/cdk": "14.x.x",
                "@angular/core": "14.x.x",
                "@angular/common": "14.x.x",
                "@angular/compiler": "14.x.x",
                "@angular/forms": "14.x.x",
                "@angular/localize": "14.x.x",
                "@angular/platform-browser": "14.x.x",
                "@angular/platform-browser-dynamic": "14.x.x",
                "@angular/animations": "14.x.x",
                "@angular/router": "14.x.x",
                "@taiga-ui/cdk": "3.x.x",
                "@taiga-ui/i18n": "3.x.x",
                "@taiga-ui/core": "3.x.x",
                "@taiga-ui/kit": "3.x.x",
                "@taiga-ui/icons": "3.x.x",
                // "@taiga-ui/addon-editor": "3.x.x", // Uncomment fix to get bug
                "@tinkoff/ng-dompurify": "*",
                "@tinkoff/ng-polymorpheus": "*",
                "@ng-web-apis/common": "*",
                "@tinkoff/ng-event-plugins": "*",
                "@ng-web-apis/intersection-observer": "*",
                "@ng-web-apis/mutation-observer": "*",
                "text-mask-core": "*",
                "dompurify": "*",
                "@types/dompurify": "*",
                "prosemirror-state": "*"
            },
            files: {
                'index.html': `<div id="app"></div>`,
            }
        },
        { newWindow: false }
    );
</script>

```
</details>

Everything is nice. All required dependencies is installed.
<img height="500" alt="deps" src="https://user-images.githubusercontent.com/35179038/202417857-49922889-7463-4da9-ab73-f733f02c2563.png">

2. Open this HTML-file

<details open>
<summary><strong>HTML-file starter WITH BUG</strong></summary>

```html
<script type="module">
    import sdk from 'https://unpkg.com/@stackblitz/sdk@1/bundles/sdk.m.js';

    sdk.openProject(
        {
            title: `Taiga UI Starter`,
            template: `angular-cli`,
            dependencies: {
                "@angular/cdk": "14.x.x",
                "@angular/core": "14.x.x",
                "@angular/common": "14.x.x",
                "@angular/compiler": "14.x.x",
                "@angular/forms": "14.x.x",
                "@angular/localize": "14.x.x",
                "@angular/platform-browser": "14.x.x",
                "@angular/platform-browser-dynamic": "14.x.x",
                "@angular/animations": "14.x.x",
                "@angular/router": "14.x.x",
                "@taiga-ui/cdk": "3.x.x",
                "@taiga-ui/i18n": "3.x.x",
                "@taiga-ui/core": "3.x.x",
                "@taiga-ui/kit": "3.x.x",
                "@taiga-ui/icons": "3.x.x",
                "@taiga-ui/addon-editor": "3.x.x", // BUG!
                "@tinkoff/ng-dompurify": "*",
                "@tinkoff/ng-polymorpheus": "*",
                "@ng-web-apis/common": "*",
                "@tinkoff/ng-event-plugins": "*",
                "@ng-web-apis/intersection-observer": "*",
                "@ng-web-apis/mutation-observer": "*",
                "text-mask-core": "*",
                "dompurify": "*",
                "@types/dompurify": "*",
                "prosemirror-state": "*"
            },
            files: {
                'index.html': `<div id="app"></div>`,
            }
        },
        { newWindow: false }
    );
</script>

```
</details>

The dependencies are not installed (all of them)!
<img height="500" alt="no-deps" src="https://user-images.githubusercontent.com/35179038/202417665-2af3bddd-6885-4d16-9f0e-f7f3514bc0e8.png">

### **Expected Behavior**
All dependencies are installed.
Or at least Stackblitz throws descriptive error what goes wrong.

**Additional Context/Questions**
We are looking forward to bug fix because we actively use Stackblitz inside our [Taiga UI](https://github.com/Tinkoff/taiga-ui).
We will really appreciate if you can handle this.

**Comment by AleksandrSl** [comment] 2022-11-17 10:29
Hi, thanks for the issue. 
Trying to install "@taiga-ui/addon-editor" gives me 
![Screenshot from 2022-11-17 13-25-58](https://user-images.githubusercontent.com/15820496/202422573-5678ba16-2fb6-4377-8417-c2b096e6ede5.png). We will take a look

**Comment by splincode** [comment] 2022-11-17 10:31
But you can install that package from npm:
https://www.npmjs.com/package/@taiga-ui/addon-editor

**Comment by splincode** [comment] 2022-11-17 10:32
Maybe related

https://github.com/ueberdosis/tiptap/issues/3420
https://github.com/ueberdosis/tiptap/issues/3000

**Comment by splincode** [comment] 2022-11-17 10:33
Hmm `null@1.1.3`

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/12021443/202423554-2b3e36bb-5bd9-4deb-b05a-44a88ffcb2ee.png">

**Comment by markwhitfeld** [comment] 2022-11-17 15:04
After some investigation, the underscore in the `@_ueberdosis/prosemirror-tables` package name is causing the issues.
We have updated to the latest version of the `npm-package-arg` library and it handles the package name parsing perfectly.
Apparently the underscore is not compliant with the npm package scope specs, but because packages were published with this naming, support has now needed to be added.
The fix will be released to production shortly.

**Comment by markwhitfeld** [comment] 2022-11-18 19:55
The fix for the issue has been deployed and confirmed working 👍

**Closed by markwhitfeld** 2022-11-18 19:55 UTC
Labels: Type: Bug, Status: Triage
