### ISSUE TITLE
Very frustrating issue when switching tabs

### ISSUE THREAD

**Issue by gspassky** [stackblitz/core#1434] opened 2021-04-26 15:57 UTC
Dear guys,

First of all, thank you for this marvelous product. However, some days ago you made an update which makes your UX worse.
Now, when I edit some code in one tab, then switch to another, and go back to the first one - cursor moves to the top of the code.

It's very, very dissapointing... Makes coding take much more time because of this little problem.

**Comment by sulco** [comment] 2021-04-26 17:15
Hi @gspassky! Thanks for the kind words and for submitting the issue! Yeah, it looks like we might have introduced a regression a couple of updates ago. I will take a look into that and let you know as soon as the fix is ready!

**Comment by sulco** [comment] 2021-04-29 16:26
Hey @gspassky, happy to report the issue is now fixed :)

**Closed by sulco** 2021-04-29 16:26 UTC
Labels: bug, fe
