### ISSUE TITLE
stackblitz stuck in" connecting to dev server"

### ISSUE THREAD

**Issue by bfheythem** [stackblitz/core#1069] opened 2019-10-02 15:51 UTC
Hello, 
I wasn't able to access the content on this website" https://stackblitz.com/" 
(Ex: https://stackblitz.com/edit/react-bmhwck?file=index.html),

![image](https://user-images.githubusercontent.com/22716581/66060043-ec7a2a00-e534-11e9-9aa6-1af432f142e2.png)

The problem is that I can see the project structure and access all the files in there, however, the compiled app cannot be seen on the page ( the actual Web app in this example ).
I tried to tracert on Command line and it gave this : 
![image](https://user-images.githubusercontent.com/22716581/66060014-dec4a480-e534-11e9-9607-12e73fb9d85e.png)

Thanks in advance,

**Comment by didkobravo** [comment] 2019-10-08 10:50
This is pretty annoying I wish stackblitz address and fix this soon.

I've found that if you open an editor for the same project in separate tab in that same browser.
Then you're going to be able to open the preview link.

Just opening... https://<some-project-name>.stackblitz.io
won't work.

1st opening.... https://stackblitz.com/edit/<some-project-name>
and then.. https://<some-project-name>.stackblitz.io
will work ....¯\_(ツ)_/¯

**Comment by Christopher-Hayes** [comment] 2019-10-31 07:00
Possible duplicate of #1057

**Comment by purplem1lk** [comment] 2021-05-22 20:32
Thank you for your patience - Attached is a screenshot of what I see when I go to your project link. It's possible that code changes made since the inception of this issue have fixed it. If your issue persists, feel free to tag me or ask to reopen this issue with screenshots of your error. Thank you! :) 

![Screen Shot 2021-05-22 at 4 29 43 PM](https://user-images.githubusercontent.com/49956513/119239989-ede9d300-bb1a-11eb-915c-47f115c2b525.png)

**Closed by purplem1lk** 2021-05-22 20:32 UTC

**Comment by juanurcola** [comment] 2021-06-10 14:42
Hi ! @purplem1lk 

I have this problem too, but when open proyect in new window (full screen) from a mobile (ios or android)
Example: 
This is my project to test: 
https://stackblitz.com/edit/web-platform-tthqhx

The URL to accest direct is : https://web-platform-tthqhx.stackblitz.io/

If this URL open in a browser desktop, it work OK. 
![image](https://user-images.githubusercontent.com/12263480/121545334-d054ae80-c9e0-11eb-9034-f4a6e193bf95.png)

But if I open this in mobile, not. 
![image](https://user-images.githubusercontent.com/12263480/121545386-dcd90700-c9e0-11eb-98df-c331fd305835.png)


Regards!

**Comment by Chirawat** [comment] 2021-07-22 08:16
> Hi ! @purplem1lk
> 
> I have this problem too, but when open project in new window (full screen) from a mobile (ios or android)
> Example:
> This is my project to test:
> https://stackblitz.com/edit/web-platform-tthqhx
> 
> The URL to accest direct is : https://web-platform-tthqhx.stackblitz.io/
> 
> If this URL open in a browser desktop, it work OK.
> ![image](https://user-images.githubusercontent.com/12263480/121545334-d054ae80-c9e0-11eb-9034-f4a6e193bf95.png)
> 
> But if I open this in mobile, not.
> ![image](https://user-images.githubusercontent.com/12263480/121545386-dcd90700-c9e0-11eb-98df-c331fd305835.png)
> 
> Regards!

I have the same problem

**Comment by SomsubhroChakraborty** [comment] 2024-03-15 15:46
The same problem is also happen to me in my case the page is completely blank . 
![Screenshot (358)](https://github.com/stackblitz/core/assets/140301396/6756c0f1-048c-459d-8f9b-485344a62834)
![Screenshot (359)](https://github.com/stackblitz/core/assets/140301396/11825cc8-b1c0-45c2-b316-d20316e4f71a)
