### ISSUE TITLE
CommonJS primitives as default export aren't automatically default value (SystemJS issue)

### ISSUE THREAD

**Issue by martinschayna** [stackblitz/core#55] opened 2017-08-08 15:59 UTC
Dependency was properly installed, but every use causes a bug.
```js
import shortid from 'shortid';

class App extends Component {
  constructor() {
    super();
    this.state = {
      name: 'React',
      id: shortid.generate()   // <--- Cannot convert object to primitive value error
    };
  }
```
https://stackblitz.com/edit/react-j3mvm3

**Comment by EricSimons** [comment] 2017-08-08 17:51
Found the root cause of the problem — looks like an edge case reg how CommonJS modules work 😅  Working on a fix now! Thanks for reporting this 🍻

**Comment by EricSimons** [comment] 2017-08-10 00:42
This is now fixed & live in prod (thanks for the hotfix @guybedford!)

@martinschayna can you try using `shortid` and see if it works on your end? Will reopen issue if you report any problems!

**Closed by EricSimons** 2017-08-10 00:42 UTC
Labels: bug
