### ISSUE TITLE
Desperately need an undo feature!

### ISSUE THREAD

**Issue by james-c-m-kim** [stackblitz/core#177] opened 2017-10-24 01:57 UTC
The UI lets me delete entire folders and skips the confirmation dialog, and I end up missing entire directories...

**Comment by mattblackdev** [comment] 2017-10-24 03:39
Dang that sucks. What's almost as bad is when you have an amazing idea, bust out a new Stackblitz project and for a few hours it's going really good. Then you accidentally scroll too far to the left in Chrome and you're back on the Stackblitz homepage and realized you never hit cmd+s once.

**Comment by james-c-m-kim** [comment] 2017-10-24 04:07
After a lot (as in a flat of Mountain Dew) of noob errors on my part, I'm
finally getting the hang of StackBlitz. It's pretty sweet to have it
transpile as you work, it's waaaay better than cough-Atom-cough, or
cough-VS Code-cough. It takes a lot of concentration not to screw something
up, though, LOL. It is a browser, after all. Wish we could port this
sweetness into an Electron app!!!

**Comment by EricSimons** [comment] 2017-10-25 01:22
@james-c-m-kim hmm that's really odd, we have confirmation dialogs for all delete operations 🤔  I'm thinking that it might be actually due to an unintentional drag and drop within the files pane? That's def happened to me once or twice — I'm looking into adding a delay or something that would fix! (Also, would love to hear more about why you'd like StackBlitz to be an electron app! :)

@mattblackdev yikes, that's happened to you?? What browser/OS are you using? We have dirty detection in the editor that throws a prompt if you try and redirect your browser away without saving - super weird that it isn't activating for you. Any other info to help me repro/debug this would be super appreciated 👍 

Really sorry about these random errors guys — we're doing our best to get this thing fully stable! Def lots of work ahead for our 2 man team 😅

**Comment by james-c-m-kim** [comment] 2017-10-25 06:09
Hi Eric,

Yeah, I think it's probably due to unintentional drag-drop. I was trying to
resolve some errors, and clicking from one file to the next, and next thing
I knew, an entire folder had disappeared. Maybe a checkable option to force
a confirmation on drag-and-drop operations (for guys like me)?

I've learned to be a much slower clicker (LOL) and that has helped a bit.
You've done an awesome job so far, thanks for all your hard work!!!



Cheers,
James

**Comment by mattblackdev** [comment] 2017-10-26 02:50
@EricSimons It's not happening anymore. I just tested it with the scroll left, back button, cmd+w and cmd+q. I'm getting the confirmation dialog in all cases. I think Chrome auto updates on my mac so it could've been a regression in a previous version.

My system right now is:
macOS Sierra 10.12.6
Chrome: Version 62.0.3202.62 (Official Build) (64-bit)

**Comment by sunilthakur** [comment] 2019-01-03 14:56
Is there any way to recover the deleted project. Please help!!

**Comment by kc0tlh** [comment] 2023-08-23 09:37
This issue is resolved in our new VS Code editor!

1) We have added Undo (CTRL + Z and CMD + Z)
2) Changes are stored in browser cache in case the page is closed without saving
3) Github is now supported for Version Control, creating additional redundancy (see Github issue #2473 for more info)

**Closed by kc0tlh** 2023-08-23 09:37 UTC
