### ISSUE TITLE
Can't run the demo. Gives an error

### ISSUE THREAD

**Issue by Myonsite** [stackblitz/core#2625] opened 2023-07-08 12:16 UTC
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by fvsch** [comment] 2023-07-10 10:03
Hi @Myonsite,

I’m closing this issue because it does not contain any actionable information. In particular, you did not fill out the requested issue template (no description, no steps to reproduce).

If you're still running into this problem, feel free to create a new issue with more information.

**Closed by fvsch** 2023-07-10 10:03 UTC
