### ISSUE TITLE
Would this tool support emmet?

### ISSUE THREAD

**Issue by hstarorg** [stackblitz/core#91] opened 2017-08-17 01:06 UTC
I used the online tool, and I want to use emmet for html file. Would you provide the function?

**Comment by lazarljubenovic** [comment] 2017-09-07 19:39
It's not yet supported.

Duplicate of https://github.com/stackblitz/core/issues/25.

**Comment by hstarorg** [comment] 2017-09-09 05:04
I have a lib: [https://github.com/hstarorg/emmet-monaco](https://github.com/hstarorg/emmet-monaco), maybe it can be used.

**Comment by EricSimons** [comment] 2019-11-06 20:08
Shipped a while back! 🍻

**Closed by EricSimons** 2019-11-06 20:08 UTC
