### ISSUE TITLE
Terminal isn't working

### ISSUE THREAD

**Issue by ahnsw0** [stackblitz/core#3001] opened 2024-03-01 14:03 UTC
### Describe the bug

The terminal won't work and won't let me type anything when I'm in a node.js project
![image](https://github.com/stackblitz/webcontainer-core/assets/123399463/390197de-f5ef-4a5c-831d-88699ec7509a)

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-rowjno?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js,index.html,styles.css&title=node.new%20Starter

### Steps to reproduce

1. Go to Dashboard
2. Click on create new project
3. Click on Node-Starter
4. Try to type on the terminal(won't work)

### Expected behavior

I expected the terminal to work and let me install the node dependencies and start the server.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/123399463/fb97ff8e-77dd-4c7c-aed7-498469f81bb9)

### Platform

```
Browser name  = Chrome
Full version  = 121.0.0.0
Major version = 121
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 113008771,
  "usedJSHeapSize": 104957659,
  "jsHeapSizeLimit": 2094792704
}
Hash = c9a8a620
```

### Additional context

This might be a bug that rarely happens but this happened like 2 times for me. It should be able to work for others, I just don't know why it doesn't for me.

**Comment by SOM-fermonte** [comment] 2024-03-13 00:25
This is a duplicate of [issue 2996](https://github.com/stackblitz/core/issues/2996), or at least seems related to it. In my case, Edge is the problem. Chrome works as expected for me.

**Comment by HeyGarrison** [comment] 2024-03-13 18:09
Duplicate of #2996

**Closed as completed by HeyGarrison** 2024-03-13 18:09 UTC
