### ISSUE TITLE
Stackblitz fails for all Angular.io examples

### ISSUE THREAD

**Issue by larsm11** [stackblitz/core#2609] opened 2023-06-30 15:28 UTC
Error in /turbo_modules/@angular/common@16.1.3/fesm2022/common.mjs (74:155)
Cannot read properties of undefined (reading 'Injectable')

**Comment by fvsch** [comment] 2023-07-03 14:09
Hi @larsm11,

I checked the angular.io site and so far have not found a failing example.
Can you point me to a page where the StackBlitz example fails?

**Comment by kc0tlh** [comment] 2023-08-24 18:46
Closing due to lack of reproduction. All examples appear to functioning properly now!

**Closed by kc0tlh** 2023-08-24 18:46 UTC
Labels: Type: Bug, Status: Needs Info
