### ISSUE TITLE
Angular not working

### ISSUE THREAD

**Issue by SamShekhovtsov** [stackblitz/core#1684] opened 2021-12-03 20:18 UTC
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
I forked a project from Angular 6 and changed references to Angular 13. 
Now it constantly shows me message: Can't find packages:
@angular/core 
@angular/platform-browser-dynamic 
@angular/platform-browser
@angular/forms

no matter what I try

### **Steps to Reproduce**
1. Go to ['https://stackblitz.com/edit/angular-scss-demo-y73bct?file=src%2Findex.html'](https://stackblitz.com/edit/angular-scss-demo-y73bct?file=src%2Findex.html)
2. See error

### **Expected Behavior**
The project runs fine

**Comment by SamShekhovtsov** [comment] 2021-12-04 21:13
actually that problem was solved by Enabling Ivy in the project settings. Now another problem appears: 

Error occurred:
Unexpected token '<'

I've added that project to github, after that I've pulled project locally and verified that it works fine. So now I have project working fine locally but failing on Stackblitz. Please take a look at this problem.

**Comment by markwhitfeld** [comment] 2021-12-09 11:13
This is potentially related to Angular 13 support, which is supported as of yesterday.
Closing as duplicate of #1657.

**Closed by markwhitfeld** 2021-12-09 11:13 UTC
Labels: Type: Bug, Status: Triage
