### ISSUE TITLE
Fatal Error while trying to use the react-html-parser package

### ISSUE THREAD

**Issue by sgaseretto** [stackblitz/core#76] opened 2017-08-13 06:32 UTC
I'm trying to render an sgv but when using the function HTMLReactParser like this:
`<div>
    	{HTMLReactParser(Viz("digraph { a -> b; }", { format: "svg", scale: 2 }))}
    </div>`

the editor throws me the following error:

`Fatal error:
Cannot read property 'prototype' of undefined
Evaluating https://unpkg.com/htmlparser2@3.9.2/lib/Parser.js
Evaluating https://unpkg.com/htmlparser2@3.9.2/lib/index.js
Evaluating https://unpkg.com/react-html-parser@1.0.3/lib/HtmlParser.js
Evaluating https://unpkg.com/react-html-parser@1.0.3/lib/index.js
Evaluating index.js
Loading app`

**Comment by EricSimons** [comment] 2017-08-13 06:38
Can you link your project's URL so I can repro & debug?                                 -Eric                                                                                                                                                                            From: notifications@github.comSent: August 12, 2017 8:32 PMTo: core@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [stackblitz/core] Fatal Error while trying to use the react-html-parser package (#76)  I'm trying to render an sgv but when using the function HTMLReactParser like this
<div> {HTMLReactParser(Viz("digraph { a -> b; }", { format: "svg", scale: 2 }))} </div>
the editor throws me the following error:
Fatal error: Cannot read property 'prototype' of undefined Evaluating https://unpkg.com/htmlparser2@3.9.2/lib/Parser.js Evaluating https://unpkg.com/htmlparser2@3.9.2/lib/index.js Evaluating https://unpkg.com/react-html-parser@1.0.3/lib/HtmlParser.js Evaluating https://unpkg.com/react-html-parser@1.0.3/lib/index.js Evaluating index.js Loading app

**Comment by sgaseretto** [comment] 2017-08-13 06:44
Here it is [https://stackblitz.com/edit/react-graphviz](url)

**Comment by EricSimons** [comment] 2017-08-13 07:42
@sgaseretto I think I found the root cause — it looks like ReactHTMLParser relies on the package `htmlparser2` which apparently requires node libs like buffer, stream, etc but doesn't list them as dependencies (they prob assume it's running in a node process :).

I'm currently on vacation but I'll try and get a fix in for this within the next day or two - will circle back once it's online. Thanks so much for reporting this! 🍻

**Comment by EricSimons** [comment] 2017-08-21 22:23
This is now fixed in prod! Check it out here -> https://stackblitz.com/edit/react-graphviz

Thanks again for reporting this & def let us know if you find any other bugs 🍻

**Closed by EricSimons** 2017-08-21 22:23 UTC
Labels: bug
