### ISSUE TITLE
Import error, can't find file: ./common  StackBlitz

### ISSUE THREAD

**Issue by jek28** [stackblitz/core#1173] opened 2020-01-31 11:29 UTC
Hi everyone, 
I'm working on Stackblitz and I have got an error "Import error, can't find file:
./common" exaxtly when I try to import socket.io from the following command:

import * as io from "socket.io-client";

Seems that socketIO needs this folder or something like that?
Thanks in advice. 

 Link to stackblitz: https://stackblitz.com/edit/angular-swanalyzer?file=src%2Fapp%2Fsql.service.ts

**Comment by EricSimons** [comment] 2020-02-10 23:11
Hey @jek28 - I just checked your link but couldn't find the error, were you able to resolve this?

Closing for now but happy to reopen if still an issue!

**Closed by EricSimons** 2020-02-10 23:11 UTC

**Comment by mak-thevar** [comment] 2020-04-15 16:25
Hey @EricSimons even I am facing the same issue.
**Steps to reproduce :**
 - just try to install a package socket.io-client 
 - try to import that in the root file.


**it throws and error** 
![image](https://user-images.githubusercontent.com/40656217/79361957-99f9db80-7f63-11ea-8f88-c09117d08df4.png)

**Comment by justvamp** [comment] 2020-07-01 08:28
Still experiencing this issue.
Reproduce example: https://stackblitz.com/edit/angular-ivy-qzhmby
Any help is appreciated.

**Comment by anees-kodappana** [comment] 2021-05-20 15:31
the issue is still there

eg: https://stackblitz.com/edit/primeng-multiselect-placeholder-d84vpm?file=src%2Fapp%2Fapp.component.ts
