### ISSUE TITLE
Development server not working

### ISSUE THREAD

**Issue by amit-bisht** [stackblitz/core#2249] opened 2023-01-10 12:02 UTC
Development server not working

**Comment by markwhitfeld** [comment] 2023-01-18 19:58
Difficult to determine the issue from the description. Potentially a duplicate of #2253
Fix was released on Monday and there has been no recurrence.
This should be resolved now. Closing issue.
If this issue is something different then please reopen an issue with more details and a reproduction.

**Closed by markwhitfeld** 2023-01-18 19:58 UTC
