### ISSUE TITLE
looks like lazy loading doesnot work for ionic projects

### ISSUE THREAD

**Issue by glongchi** [stackblitz/core#652] opened 2018-08-19 21:43 UTC
keep getting error in console: for this case we are lazy loading a menu page
ERROR
Error: Uncaught (in promise): invalid link: menu

**Comment by 7martinelli** [comment] 2018-08-29 16:33
that's the same issue as #632 . let's keep in the same line

**Comment by purplem1lk** [comment] 2021-04-27 13:36
Closing this issue, as it is a duplicate of #632. If you have any questions, feel free to tag me or continue the conversation in #632. Thank you! :)

**Closed by purplem1lk** 2021-04-27 13:36 UTC
