### ISSUE TITLE
the console color is lack of contrast 

### ISSUE THREAD

**Issue by lovetingyuan** [stackblitz/core#1460] opened 2021-05-22 11:16 UTC
### **Description of Bug**
the console color is lack of contrast 

![image](https://user-images.githubusercontent.com/7310471/119224675-221cbe00-bb32-11eb-9b4b-0f76f8685277.png)

How to fix it?

**Comment by PrinceRajRoy** [comment] 2021-05-23 11:04
@lovetingyuan you could use 
```js
    console.log('%c YOUR_TEXT', 'color:white');
```
till they fix it

**Comment by purplem1lk** [comment] 2021-05-24 17:46
Thank you for posting this issue! This issue will be closed accordingly as it is a duplicate of #1450 and has already been responded to by one of our StackBlitz devs. If you have any questions, feel free to tag me or continue the conversation in #1450 to keep all conversation/resolution together. Thank you! :)

**Closed by purplem1lk** 2021-05-24 17:46 UTC
Labels: Status: Triage, Type: Bug

**Comment by purplem1lk** [comment] 2021-06-08 14:05
Hey @lovetingyuan, #1450 was updated and the devs have fixed this issue. Feel free to tag me if you are still running into this issue. Thanks!
