### ISSUE TITLE
HTML/CSS/JavaScript: Error: ENOENT, no such file or directory "/~"

### ISSUE THREAD

**Issue by PrithviSathish** [stackblitz/core#2037] opened 2022-09-07 16:30 UTC
I wasn't sure about the reason for the error, so I removed all the in-built code and then ran simple html and got the same error. It turns out that the error persists even after removing all the contents of the file. So I guess this is some internal issues which requires to be fixed

**Comment by AleksandrSl** [comment] 2022-09-09 17:48
Could you provide us more details please? Browser/operating system, or any other details

This is the video with up and running HTML/CSS/Javascript project, everything seems to be working fine. 
Taken under Fedora 34, Vivaldi 5.4.2753.37 (Stable channel) stable (64-bit)  Chromium 104 based.
https://user-images.githubusercontent.com/15820496/189412310-87579730-4e6f-4588-93b8-f161ff504811.mp4

**Comment by PrithviSathish** [comment] 2022-09-11 06:09
I use Firefox 104.0.2 (64-bit) version, Windows 11 Operating System. The issue seems to be resolved while using a chromium based browser such as Microsoft Edge. Please fix this issue for Firefox browser.
Below is the screenshot while creating a HTML/CSS/Javascript file in Stackblitz using Firefox browser:

![image](https://user-images.githubusercontent.com/73330717/189514835-29377039-fbf1-4ef1-90e9-6515783ac28c.png)

**Comment by AleksandrSl** [comment] 2022-09-11 06:42
Thank you! Could reproduce this in FF, we will take a look

**Comment by andsheterliak** [comment] 2022-11-23 03:47
Duplicate of #1679

**Comment by fvsch** [comment] 2023-04-11 18:59
Closing as a duplicate of #1679.

**Closed by fvsch** 2023-04-11 18:59 UTC
