### ISSUE TITLE
No preview for static website.

### ISSUE THREAD

**Issue by naidu-kotha** [stackblitz/core#2341] opened 2023-02-15 20:18 UTC
### **Description of Bug**
I'm unable to see the preview of the default static website. If I open the URL it just keeps on showing the loader. Even if I make any changes to html file and save it, nothing changes.

### **Steps to Reproduce**

1. Go to 'Frontend'
2. Click on 'static'

![image](https://user-images.githubusercontent.com/114652278/219142812-1b78e75e-3ef7-4293-81bd-1c754c9a696b.png)
![image](https://user-images.githubusercontent.com/114652278/219143091-d6dce2a4-545b-48c2-809d-152c53c5bab0.png)
![image](https://user-images.githubusercontent.com/114652278/219143634-e80de890-fa3a-4426-bbcc-9e146aa9de58.png)

URL - https://web-platform-e3aq9n.stackblitz.io/

**Comment by splincode** [comment] 2023-02-16 13:06
I have same issue

**Comment by kc0tlh** [comment] 2023-08-25 00:36
Closing as duplicate of #162. This docs page on [configuring various different browser to work with StackBlitz](https://developer.stackblitz.com/platform/webcontainers/browser-config) should resolve your issues. Please let me know if not and we can re-open the issue!

**Closed by kc0tlh** 2023-08-25 00:36 UTC
Labels: Type: Bug, Status: Triage, Tech: EngineBlock
