### ISSUE TITLE
Static projects

### ISSUE THREAD

**Issue by Legionario-byte** [stackblitz/core#2387] opened 2023-03-02 11:42 UTC
it seems that static project pages don't reload on code change, is it a bug?

**Comment by fvsch** [comment] 2023-03-02 12:07
Hi @Legionario-byte, thanks for the report!

Yup, it's a known issue, we're going to ship a fix for it today.

Closing as a duplicate of #2385, you can follow updates there.

**Closed by fvsch** 2023-03-02 12:07 UTC
