### ISSUE TITLE
Webcontainer unable to resolve node_module exports.

### ISSUE THREAD

**Issue by john-fenton** [stackblitz/core#2456] opened 2023-04-04 03:55 UTC
#### Unable to resolve package exports.

I have a hunch that this is caused by the the manner in which [`angular2-wizard`](https://github.com/maiyaporn/angular2-wizard/blob/master/index.ts) are exporting these components from their library in index.ts:

    export * from './src/wizard.component';
    export * from './src/wizard-step.component';

My understanding is.... When Stackblitz initializes it encapsulates/sandboxes the code into a [webcontainer](https://github.com/stackblitz/webcontainer-core) environment. When it tries to resolve the `'./src/wizard.component'` routes it is most likely looking at the root `src` directory defined in the angular application instead of the correct node_modules src folder. This may explain why this works locally (as there is no webcontainer) but not here.

Error:
```
Import error, can't find files:
./src/wizard.component
./src/wizard-step.component
```

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/angular-fmkkwx?file=src%2Fmain.ts
2. Wait for compilation
4. See error in preview pane.

### **Expected Behavior**
Package routes should be resolved as expected.

**Additional Context/Questions**
https://stackoverflow.com/questions/75632961/error-when-adding-my-npm-module-to-imports/

**Comment by markwhitfeld** [comment] 2023-04-06 16:16
It looks like this problem is caused by the fact that the `angular2-wizard` has not been compiled with the new angular compiler, and is therefore incompatible with Angular 15 and upwards.
This should be locally verifiable (in a project on your local machine).

I am closing this issue because it is an issue with incompatible libraries.

**Closed by markwhitfeld** 2023-04-06 16:16 UTC
Labels: Type: Bug, Status: Triage

**Comment by john-fenton** [comment] 2023-04-06 22:39
@markwhitfeld  Please see attached a bare bones working copy of this that will run locally.

[example.zip](https://github.com/stackblitz/core/files/11174837/example.zip)
