### ISSUE TITLE
Support Github resolving for Turbo

### ISSUE THREAD

**Issue by bobbinmp** [stackblitz/core#1170] opened 2020-01-30 12:07 UTC
Hi,
When I try to install jspdf in stackblitz.com, its showing the below error.
Failure: Unsatisfied Version Range
Unable to resolve package
Please try installing a different version or range

![image](https://user-images.githubusercontent.com/762842/73448481-f434c880-4386-11ea-9436-eb6b36b4fd2e.png)

Thank You
Bobbin

**Comment by EricSimons** [comment] 2020-02-10 23:24
@bobbinmp this is due to a limitation on our npm resolver. Have added this to the roadmap to get fixed 👍

**Comment by kc0tlh** [comment] 2023-08-31 01:56
Closing as duplicate of #1195

**Closed by kc0tlh** 2023-08-31 01:56 UTC
Labels: Type: Bug
