### ISSUE TITLE
Angular sample hangs on "Instantiating bundle" when using sass

### ISSUE THREAD

**Issue by zdrawku** [stackblitz/core#894] opened 2019-03-15 15:04 UTC
Open [this angular sample](https://stackblitz.com/edit/angular-7xva2w) using`sass` on Edge. Sample bundling hangs.

Note: If the [same sample](https://stackblitz.com/edit/angular-kg3vq3) is using CSS, sample is loaded correctly.

Edge version:
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

Image result (**SASS**):
![image](https://user-images.githubusercontent.com/11193764/54440834-21af5e00-4744-11e9-91b9-e36ca165ee22.png)

Image result (**CSS**):
![image](https://user-images.githubusercontent.com/11193764/54440868-32f86a80-4744-11e9-8d03-008c867f458b.png)

**Comment by kc0tlh** [comment] 2023-08-31 05:49
Closing as duplicate of duplicate of #208. Please follow there for updates!

**Closed by kc0tlh** 2023-08-31 05:49 UTC
Labels: Type: Bug
