### ISSUE TITLE
issue with github angular-cli 6.0.0.rc3

### ISSUE THREAD

**Issue by beligh-hamdi** [stackblitz/core#411] opened 2018-04-16 13:57 UTC
<img width="922" alt="screen shot 2018-04-16 at 14 55 59" src="https://user-images.githubusercontent.com/1937958/38813252-5c809220-4186-11e8-94af-e0e3a39e0c7e.png">

https://stackblitz.com/github/influans-meetups/event-management

it's not supported yet ?

**Comment by seveves** [comment] 2018-04-16 14:33
Duplicate of #404 ... not supported yet but they are working on it 😸

**Closed by seveves** 2018-04-16 14:33 UTC
