### ISSUE TITLE
Stackblitz console Font color When Google Chrome is applied with Dark theme

### ISSUE THREAD

**Issue by divyameher** [stackblitz/core#1456] opened 2021-05-21 13:49 UTC
![image](https://user-images.githubusercontent.com/24610542/119147624-64c69380-ba69-11eb-9d09-7ae5f36d2534.png)

Font Colors in Console should be modified w.r.t Dark theme Console background

**Comment by purplem1lk** [comment] 2021-05-24 17:40
Thank you for posting this issue! This issue will be closed accordingly as it is a duplicate of #1450 and has already been responded to by one of our StackBlitz devs. If you have any questions, feel free to tag me or continue the conversation in #1450 to keep all conversation/resolution together. Thank you! :)

**Closed by purplem1lk** 2021-05-24 17:40 UTC
Labels: Type: Duplicate

**Comment by purplem1lk** [comment] 2021-06-08 14:06
Hey @divyameher, #1450 was updated and the devs have fixed this issue. Feel free to tag me if you are still running into this issue. Thanks!
