### ISSUE TITLE
package.json missing

### ISSUE THREAD

**Issue by DynamiteTom** [stackblitz/core#1660] opened 2021-11-08 14:10 UTC
I definitely have a package.json 

but stackblitz thinks I dont 

https://stackblitz.com/github.com/DynamiteTom/angular-rxjs-infinite-scroll-main

**Comment by geromegrignon** [comment] 2021-11-08 14:16
Hey @DynamiteTom,

Stackblitz expects a package.json file at the root of the project but your file is nested as the root of the project is a folder, not the project itself 9being quite an uncommon architecture on GitHub).

**Comment by SamVerschueren** [comment] 2021-11-08 15:17
You could point to that sub directory though with https://stackblitz.com/github/DynamiteTom/angular-rxjs-infinite-scroll-main/tree/master/angular-rxjs-infinite-scroll-main. 

But as @geromegrignon pointed out, I think what you wanted in the first place is to not have that sub directory?

**Comment by cipchk** [comment] 2021-11-10 13:13
Same issues, png:

![image](https://user-images.githubusercontent.com/2987467/141118878-0da2af29-c890-4d7d-8db4-df162bc80d45.png)

But it looks like random, sometimes it’s good.

Steps to reproduce:

- Go to https://ng-alain.com/form/text
- Click ![image](https://user-images.githubusercontent.com/2987467/141119369-e918cf1c-b21c-4cc1-9138-0a95eec2048a.png)

**Comment by kc0tlh** [comment] 2023-08-23 11:54
@DynamiteTom your issue appears to be resolved by @geromegrignon's suggestion and @cipchk your project is now working without any modifications. Closing this issue as resolved!

**Closed by kc0tlh** 2023-08-23 11:54 UTC
