### ISSUE TITLE
Showing import issues

### ISSUE THREAD

**Issue by Ranindu15** [stackblitz/core#2693] opened 2023-08-23 11:11 UTC
In my local machine this is working fine. Can someone please check this?

**Comment by markwhitfeld** [comment] 2023-08-23 14:01
Closing this because there is no reproduction or description of the issue.
Please use one of the provided issue templates when logging an issue:
https://github.com/stackblitz/core/issues/new/choose

**Closed by markwhitfeld** 2023-08-23 14:01 UTC
