### ISSUE TITLE
Add Snippets Support

### ISSUE THREAD

**Issue by carlesba** [stackblitz/core#27] opened 2017-08-04 21:41 UTC

**Comment by xstephen95x** [comment] 2017-08-05 16:59
Is there any way a feature such as Toggle Vim Bindings could be added? For example:
http://coolwanglu.github.io/vim.js/emterpreter/vim.html 

Some online editors have implemented Vim-like key bindings.

**Comment by virzen** [comment] 2017-08-06 20:24
Idk how much is it actually based on VSCode's source, but there is a [plugin](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) adding Vim binding to it, of course. Actually, porting VSC's plugin system would resolve this issue and enable further customizations, but I suspect it's not easy at all. 😄

**Comment by EricSimons** [comment] 2017-08-06 20:45
The VIM side of things here looks like a dupe of https://github.com/stackblitz/core/issues/20, but would love to hear more info about what kind of snippets support you're looking for!

**Comment by sulco** [comment] 2021-02-02 13:42
We now support snippets :)

https://user-images.githubusercontent.com/1511906/106608501-c28baa00-6564-11eb-97a6-9d6c8f9ec5da.mp4

**Closed by sulco** 2021-02-02 13:42 UTC
Labels: enhancement, fe
